### ISSUE TITLE
[BUG] <title>code interpreter is not working

### ISSUE THREAD

**Issue by ruifengma** [QwenLM/Qwen#1014]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Other chat is normal . Only when I try to use code interpreter, the error raised:
```
2024-01-26 14:45:45,054 - utils.py - 35 - ERROR - Traceback (most recent call last):
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 137, in _support_function_calling
    *_, last = self._chat_with_functions(messages=messages,
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 185, in _postprocess_iterator
    yield self._postprocess_convert_text_to_fncall(m)
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 283, in _postprocess_convert_text_to_fncall
    messages = self._format_msg_to_list(messages)
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 191, in _format_msg_to_list
    role = msg[ROLE]
TypeError: string indices must be integers

2024-01-26 14:45:45,054 - qwen_oai.py - 70 - INFO - Detected function calls are not supported, using chat format
Traceback (most recent call last):
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 712, in _error_catcher
    yield
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 1071, in read_chunked
    self._update_chunk_length()
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 1006, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 931, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 1059, in read_chunked
    with self._error_catcher():
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/urllib3/response.py", line 729, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/mrx/agent/Qwen-Agent/qwen_server/workstation_server.py", line 243, in bot
    for chunk in output_beautify.convert_to_full_str_stream(
  File "/data/mrx/agent/Qwen-Agent/qwen_server/output_beautify.py", line 81, in convert_to_full_str_stream
    for message_list in message_list_stream:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/agents/assistant.py", line 91, in _run
    for output in output_stream:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/base.py", line 184, in _postprocess_iterator
    for m in messages:
  File "/data/mrx/agent/Qwen-Agent/qwen_agent/llm/qwen_oai.py", line 42, in _chat_stream
    for chunk in response:
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 168, in <genexpr>
    return (
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/openai/api_requestor.py", line 702, in <genexpr>
    return (
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/openai/api_requestor.py", line 116, in parse_stream
    for line in rbody:
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/qwenagent/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/data/mrx/agent/Qwen-Agent/qwen_server/workstation_server.py", line 251, in bot
    raise ValueError(ex)
ValueError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

```
and the error on the Qwen model side is
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    async for data in self.body_iterator:
  File "/data/mrx/agent/Qwen/openai_api.py", line 442, in predict
    raise HTTPException(
fastapi.exceptions.HTTPException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/qtest/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 83, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.
```

### 期望行为 | Expected Behavior

Just want it to run normally

### 复现方法 | Steps To Reproduce

just pull the latest code base from Qwen and run with openai_api.py to deploy and run the run_server.py from QwenAgent

### 运行环境 | Environment

```Markdown
- OS:CentOS7
- Python:3.10
- Transformers:4.32.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by xrenaissance** [comment]
我也遇见同样的问题
