### ISSUE TITLE
[BUG] 使用Zero3进行qwen72B 全参数训练报错

### ISSUE THREAD

**Issue by Double-bear** [QwenLM/Qwen#1022]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在使用zero3进行全参数的qwen72Bsft时报错
```
Traceback (most recent call last):
  File "/code/xx/LLM_mine/llm-train/function_call/script/train_qwen/train.py", line 511, in <module>
    train()
  File "/code/xx/LLM_mine/llm-train/function_call/script/train_qwen/train.py", line 444, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2875, in from_pretrained
    with ContextManagers(init_contexts):
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/generic.py", line 406, in __exit__
    self.stack.__exit__(*args, **kwargs)
  File "/opt/conda/lib/python3.10/contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "/opt/conda/lib/python3.10/contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 447, in __exit__
    self.remove_wrappers()
  File "/opt/conda/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 511, in remove_wrappers
Traceback (most recent call last):
  File "/code/xx/LLM_mine/llm-train/function_call/script/train_qwen/train.py", line 511, in <module>
    raise RuntimeError(msg)
RuntimeError: `<class 'flash_attn.layers.rotary.RotaryEmbedding'>' was not properly set up for sharding by zero.Init(). A subclass of torch.nn.Module must be defined before zero.Init() where an instance of the class is created.
```
在同样的环境下使用zero2进行7B的sft则不会报错
请教一下这个应该如何解决？

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 
- Python: 3.10
- Transformers: 4.32.0
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
- Flash-attention: 2.5.0
```

**Comment by jklj077** [comment]
用的哪份代码？

**Comment by Double-bear** [comment]
> 用的哪份代码？

用的finetune.py，不过这个问题好像不是代码的问题，我把deepspeed版本升级以后就好了😅
