### ISSUE TITLE
使用QwenLM/vllm-gptq运行Qwen-14B-Chat-Int4报错：ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.

### ISSUE THREAD

**Issue by huangyunxin** [QwenLM/Qwen#1035]
### 问题1
* 我使用`QwenLM/vllm-gptq`中的`Dockerfile`构建的镜像，运行`Qwen-7B-Chat-Int4`正常
* 运行`Qwen-14B-Chat-Int4`时，使用一张显卡`--tensor-parallel-size 1`可以正常运行，改为`--tensor-parallel-size 2`后就报错，完整报错如下：
```
[root@localhost qwen-vllm-gptq]# docker logs --tail 50 qwen-vllm-gptq
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 644, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 305, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 108, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/vllm/engine/llm_engine.py", line 191, in _init_workers_ray
    self._run_workers(
  File "/workspace/vllm/engine/llm_engine.py", line 737, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/workspace/vllm/engine/llm_engine.py", line 714, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2624, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::RayWorker.execute_method() (pid=3235, ip=172.17.0.8, actor_id=dd8867d41533e08f642f105d01000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f1263e857e0>)
  File "/workspace/vllm/engine/ray_utils.py", line 31, in execute_method
    return executor(*args, **kwargs)
  File "/workspace/vllm/worker/worker.py", line 72, in load_model
    self.model = get_model(self.model_config)
  File "/workspace/vllm/model_executor/model_loader.py", line 90, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/workspace/vllm/model_executor/models/qwen.py", line 240, in __init__
    self.transformer = QWenModel(config, linear_method)
  File "/workspace/vllm/model_executor/models/qwen.py", line 199, in __init__
    self.h = nn.ModuleList([
  File "/workspace/vllm/model_executor/models/qwen.py", line 200, in <listcomp>
    QWenBlock(config, linear_method)
  File "/workspace/vllm/model_executor/models/qwen.py", line 151, in __init__
    self.mlp = QWenMLP(config.hidden_size,
  File "/workspace/vllm/model_executor/models/qwen.py", line 51, in __init__
    self.c_proj = RowParallelLinear(intermediate_size,
  File "/workspace/vllm/model_executor/layers/linear.py", line 501, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "/workspace/vllm/model_executor/layers/quantization/gptq.py", line 116, in create_weights
    raise ValueError(
ValueError: The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.
```

### 问题2
* 提问时，必须增加参数`"stop": ["<|endoftext|>","<|im_end|>","<|im_start|>"],`才能正常返回结果，否则会一直输出直到最大tokens，这样是正确的使用方式吗？

**Comment by kk19990709** [comment]
我也遇到了问题一

**Comment by jklj077** [comment]
For issue 1, it is expected due the model architecture of Qwen-14B-Int4. 13696 (intermediate size)/128 (group size in GPTQ) = 107, which cannot be dispatched to 2 or more cards.

For issue 2, as stated in README, please use FastChat+vLLM, since vLLM itself does not support the generation configurate of Qwen1.0 by default.

**Comment by Clannad47** [comment]
This is the official solution provided by QWEN，[https://qwen.readthedocs.io/zh-cn/latest/quantization/gptq.html](url)
