### ISSUE TITLE
[BUG] lora微调到1000save_steps保存模型报错，提示文件不存在

### ISSUE THREAD

**Issue by jiangliqin** [QwenLM/Qwen#1075]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

29%|███████████████████████████████████████▌                                                                                               | 1000/3415 [25:03:27<60:17:53, 89.89s/it]/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py:1879: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/finetune.py", line 374, in <module>
Traceback (most recent call last):
  File "/mnt/finetune.py", line 374, in <module>
    train()
  File "/mnt/finetune.py", line 367, in train
        train()trainer.train()

  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1537, in train
  File "/mnt/finetune.py", line 367, in train
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2383, in _save_checkpoint
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2383, in _save_checkpoint
    os.rename(staging_output_dir, output_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/output_tv_style_title/tmp-checkpoint-1000' -> '/mnt/output_tv_style_title/checkpoint-1000'
    os.rename(staging_output_dir, output_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/output_tv_style_title/tmp-checkpoint-1000' -> '/mnt/output_tv_style_title/checkpoint-1000'
Traceback (most recent call last):
  File "/mnt/finetune.py", line 374, in <module>
    train()
  File "/mnt/finetune.py", line 367, in train
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2376, in _save_checkpoint
    self.state.save_to_json(os.path.join(staging_output_dir, TRAINER_STATE_NAME))
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer_callback.py", line 114, in save_to_json
    with open(json_path, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/output_tv_style_title/tmp-checkpoint-1000/trainer_state.json'
 29%|███████████████████████████████████████▌                                                                                               | 1000/3415 [25:04:10<60:32:34, 90.25s/it]
[2024-02-20 02:23:30,875] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 95 closing signal SIGTERM
[2024-02-20 02:23:31,341] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 94) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

### 复现方法 | Steps To Reproduce

执行脚本finetune_lora_ds.sh

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.8
- Transformers:4.36.0
- PyTorch:2.1.1
- CUDA :12.1
```

**Comment by jklj077** [comment]
According to the error log, it appears that multiple jobs are attempting to save their checkpoints in the same directory concurrently. To avoid conflicts and potential data loss, please ensure that only a single job has write access to this checkpoint directory at any given time.

Moreover, since you're utilizing `finetune_lora_ds.sh` which is designed for multi-node multi-GPU finetuning, it's essential to verify if the distributed arguments (such as host addresses, world size, and rank) are correctly configured. Misconfiguration in these settings could lead to unintended parallel writes to the shared checkpoint directory. Please double-check your setup to guarantee proper synchronization and coordination among the different processes or nodes during training.

**Comment by jiangliqin** [comment]
GPUS_PER_NODE=4
NNODES=1
我是在单机4卡张并行训练的，不是多节点，检查了finetune_lora_ds配置：

#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

GPUS_PER_NODE=4
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="/mnt/Qwen-14B-Chat"
DATA="/mnt/data/finetune.json"

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS /mnt/finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --fp16 True \
    --output_dir /mnt/output_tv_style_title \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --lazy_preprocess True \
    --use_lora \
    --gradient_checkpointing \
    --deepspeed /mnt/finetune/ds_config_zero3.json

**Comment by WangJianQ-cmd** [comment]
使用绝对地址试一下呢？

**Comment by jiangliqin** [comment]
脚本中的/mnt就是容器的绝对地址，虽然保存报错，我看实际有保存模型文件 @WangJianQ-cmd
