### ISSUE TITLE
[BUG] <title>cannot import name 'allow_in_graph' from partially initialized module 'torch._dynamo' (most likely due to a circular import) (/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/_dynamo/__init__.py)

### ISSUE THREAD

**Issue by dshwei** [QwenLM/Qwen#1173]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

qwen_motion
```
Traceback (most recent call last):
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/generation/utils.py", line 27, in <module>
    from ..deepspeed import is_deepspeed_zero3_enabled
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/deepspeed.py", line 37, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/accelerate/__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 172, in <module>
    from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/accelerate/utils/fsdp_utils.py", line 26, in <module>
    import torch.distributed.checkpoint as dist_cp
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/checkpoint/__init__.py", line 7, in <module>
    from .state_dict_loader import load_state_dict, load
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/checkpoint/state_dict_loader.py", line 12, in <module>
    from .default_planner import DefaultLoadPlanner
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/checkpoint/default_planner.py", line 14, in <module>
    from torch.distributed._tensor import DTensor
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/_tensor/__init__.py", line 346, in <module>
    import torch.distributed._tensor._dynamo_utils
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/_tensor/_dynamo_utils.py", line 1, in <module>
    from torch._dynamo import allow_in_graph
ImportError: cannot import name 'allow_in_graph' from partially initialized module 'torch._dynamo' (most likely due to a circular import) (/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/_dynamo/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/demo/project/LLM/Qwen/finetune.py", line 12, in <module>
    from deepspeed import zero
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/__init__.py", line 25, in <module>
    from . import ops
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/ops/__init__.py", line 6, in <module>
    from . import adam
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/ops/adam/__init__.py", line 6, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 8, in <module>
    from deepspeed.utils import logger
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/utils/__init__.py", line 10, in <module>
    from .groups import *
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/utils/groups.py", line 28, in <module>
    from deepspeed import comm as dist
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/comm/__init__.py", line 7, in <module>
    from .comm import *
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 31, in <module>
    from deepspeed.comm.ccl import CCLBackend
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/comm/ccl.py", line 12, in <module>
    from .torch import TorchBackend
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 100, in <module>
    class TorchBackend(Backend):
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 125, in TorchBackend
    def get_all_gather_function(self):
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/deepspeed/runtime/compiler.py", line 21, in disable
    return torch.compiler.disable(func)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/compiler/__init__.py", line 93, in disable
    import torch._dynamo
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/_dynamo/allowed_functions.py", line 30, in <module>
    from .utils import hashable, is_safe_constant, NP_SUPPORTED_MODULES
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 5, in <module>
    import cProfile
  File "/demo/miniconda3/envs/qwen/lib/python3.9/cProfile.py", line 11, in <module>
    import profile as _pyprofile
  File "/demo/project/LLM/Qwen/profile.py", line 27, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 174, in check_imports
    importlib.import_module(imp)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers_stream_generator/__init__.py", line 1, in <module>
    from .main import init_stream_support
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers_stream_generator/main.py", line 1, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1121, in __getattr__
    value = getattr(module, name)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'allow_in_graph' from partially initialized module 'torch._dynamo' (most likely due to a circular import) (/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/_dynamo/__init__.py)
[2024-03-27 10:16:19,785] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2368232) of binary: /demo/miniconda3/envs/qwen/bin/python
srun: error: zibo-gpu-18: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/demo/miniconda3/envs/qwen/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/demo/miniconda3/envs/qwen/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-27_10:16:19
  host      : zibo-gpu-18.maas
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2368232)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

### 复现方法 | Steps To Reproduce

transformers==4.32.0
accelerate
tiktoken
einops
transformers_stream_generator==0.0.4
scipy
deepspeed

### 运行环境 | Environment

```Markdown
- OS:ubuntu
- Python:3.9
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

```
#!/bin/bash

#SBATCH --job-name=sql_train_fy                           # name
#SBATCH --nodes=1                                      # nodes
#SBATCH -w zibo-gpu-[18] 
#SBATCH --ntasks-per-node=1                            # crucial - only 1 task per dist per node!
#SBATCH --cpus-per-task=8                              # number of cores per tasks
#SBATCH --gres=gpu:1                                   # number of gpus
#SBATCH --gpus-per-task=1                             # number of gpus
#SBATCH --output=/demo/workspace/log/%x-%j.out     # output file name

export GPUS_PER_NODE=1
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=9901

export https_proxy="http://10.31.19.10:7890"
export http_proxy="http://10.31.19.10:7890"

DATA="/demo/project/LLM/Qwen/1000个心理咨询问答.xlsx"
DATA="/demo/project/LLM/Qwen/data.json"
DS_CONFIG_PATH="finetune/ds_config_zero2.json"

echo "qwen_motion"

DISTRIBUTED_ARGS="
    --nproc_per_node 2 \
    --nnodes 1 \
    --node_rank 0 \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

srun --jobid $SLURM_JOBID bash -c '
    source /demo/miniconda3/bin/activate && \
    conda activate /demo/miniconda3/envs/qwen && \
    cd /demo/project/LLM/Qwen && \
    torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path Qwen/Qwen-7B \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 3e-4 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 512 \
    --lazy_preprocess True \
    --gradient_checkpointing \
    --use_lora \
    --deepspeed finetune/ds_config_zero2.json
'
```

**Comment by jklj077** [comment]
```
...
File "/demo/project/LLM/Qwen/profile.py", line 27, in <module>
...
```

Please try removing the `profile.py` from the working directory or renaming it. It overrides the `profile` module from Python standard library.
