### ISSUE TITLE
[BUG] Qwen 1.8B 多线程推理时报错

### ISSUE THREAD

**Issue by chansonzhang** [QwenLM/Qwen#1303]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

运行下面的代码：
```python
def get_slots(query: str, prompt: str = None) -> Dict[str, str]:
    if not prompt:
        prompt = "<my prompt>"
    messages = prompt + "\n" + query

    response, history = model.chat(tokenizer, messages, history=None,
                                   temperature=0.001
                                   )
    try:
        response = json.loads(response)
    except Exception as e:
        traceback.print_exc()
        response = [{}]
    result = {s: sv for s, sv in response[0].items() if sv}
    return result


def run():
    while True:
        query = "随便什么query"
        print(f"query: {query}")
        slots: Dict[str, str] = get_slots(query=query)
        print("slots:")
        print(slots)
        print("-"*30)
if __name__ == '__main__':
    from threading import Thread
    for i in range(10):
        print(f"thread {i} start")
        t = Thread(target=run)
        t.start()
```
报错
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "slot_filling_1_8B_engine.py", line 38, in run
    slots: Dict[str, str] = get_slots(query=query)
  File "slot_filling_1_8B_engine.py", line 22, in get_slots
    response, history = model.chat(tokenizer, messages, history=None,
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 1139, in chat
    outputs = self.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 1261, in generate
    return super().generate(
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 1045, in forward
    transformer_outputs = self.transformer(
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 851, in forward
    rotary_pos_emb_list = [
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 852, in <listcomp>
    self.rotary_emb(kv_seq_len, ntk_alpha=ntk_alpha) for ntk_alpha in ntk_alpha_list
  File "/root/software/anaconda3/envs/qwen1.8b/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/modeling_qwen.py", line 1314, in forward
    cos, sin = self._rotary_pos_emb_cache
TypeError: cannot unpack non-iterable NoneType object
```

报错之后依然能正常得到结果，但是 10 线程并发时显存占用(大概6G)和GPU利用率(大概35%)相比不使用多线程时均没有增加

### 期望行为 | Expected Behavior

期望行为：
1. 多线程时不报错
2. 多线程时显存和GPU利用率成倍增加，例如 10 线程时，期望显存占用 60G，GPU 利用率达到 100%

### 运行环境 | Environment

```Markdown
- OS: ubuntu 20.04
- Python:3.8.19
- Transformers: 4.42.4
- PyTorch:2.0.0+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

**Comment by jklj077** [comment]
首先，在未作声明时，Python代码不应被视作线程安全的；其次，Python跟CUDA是两个世界的东西，Python多线程并发并不会影响GPU异步顺序执行；最后，你应该使用专业的框架，比如vllm、TGI、SGLang等，并使用Qwen2。

**Comment by chansonzhang** [comment]
> Python多线程并发并不会影响GPU异步顺序执行

@jklj077 可以详细解释下这块的原理吗？
