### ISSUE TITLE
[BUG] <title> model_max_length 32768 not work

### ISSUE THREAD

**Issue by chansonzhang** [QwenLM/Qwen#1307]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Traceback (most recent call last):
[rank0]:   File "……site-packages/transformers/tokenization_utils_base.py", line 762, in convert_to_tensors
[rank0]:     tensor = as_tensor(value)
[rank0]:   File "……site-packages/transformers/tokenization_utils_base.py", line 724, in as_tensor
[rank0]:     return torch.tensor(value)
[rank0]: ValueError: expected sequence of length 8034 at dim 1 (got 14276)

### 期望行为 | Expected Behavior

期望可以支持 32K 的长度，或者自动截断

### 复现方法 | Steps To Reproduce

finetune.py --model_max_length 32768 --use_lora True

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.8.19
- Transformers: 4.42.3
- PyTorch: 2.3.0
- CUDA 12.1
```

**Comment by chansonzhang** [comment]
according to [README](https://github.com/QwenLM/Qwen/blob/main/README.md), Qwen-7B does support 32K Max Length.
![image](https://github.com/user-attachments/assets/6652569c-e872-4e67-9eed-a598682c64cb)

**Comment by chansonzhang** [comment]
I noticed input_ids are padded to the max_length in batch, but labels are not. 
The checkpoint is at `site-packages\transformers\tokenization_utils_base.py`, line 3450

![image](https://github.com/user-attachments/assets/e9e74430-24c1-4492-8c1f-3d1f3d64cd99)
![image](https://github.com/user-attachments/assets/848dd737-0608-4c10-a536-b82763d53246)

```
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\tokenization_utils_base.py", line 762, in convert_to_tensors
    tensor = as_tensor(value)
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\tokenization_utils_base.py", line 724, in as_tensor
    return torch.tensor(value)
ValueError: expected sequence of length 6035 at dim 1 (got 6977)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\accelerate\data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\data\data_collator.py", line 271, in __call__
    batch = pad_without_fast_tokenizer_warning(
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\data\data_collator.py", line 66, in pad_without_fast_tokenizer_warning
    padded = tokenizer.pad(*pad_args, **pad_kwargs)
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\tokenization_utils_base.py", line 3450, in pad
    return BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\tokenization_utils_base.py", line 227, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "C:\ProgramData\mambaforge\envs\py38\lib\site-packages\transformers\tokenization_utils_base.py", line 778, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`labels` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
python-BaseException
```

I

**Comment by chansonzhang** [comment]
When I change the model from `Qwen1.5-7B-Chat` to `Qwen2-7B-Instruct`, the same error is still there.
