### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by bxhsort** [QwenLM/Qwen#1326]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Traceback (most recent call last):
  File "/root/autodl-tmp/Qwen/finetune.py", line 374, in <module>
    train()
  File "/root/autodl-tmp/Qwen/finetune.py", line 363, in train
    trainer = Trainer(
  File "/root/miniconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 340, in __init__
    self.create_accelerator_and_postprocess()
  File "/root/miniconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 3883, in create_accelerator_and_postprocess
    self.accelerator = Accelerator(
TypeError: Accelerator.__init__() got an unexpected keyword argument 'dispatch_batches'

### 运行环境 | Environment

```Markdown
- OS: linux
- Python: 3.10
- Transformers: 4.32.0
- PyTorch: 2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by guoping1127** [comment]
我也有这个错误
