### ISSUE TITLE
[BUG] modelscope pipeline不支持quantization_config

### ISSUE THREAD

**Issue by shaoyaoqian** [QwenLM/Qwen#244]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks
from transformers import BitsAndBytesConfig
import torch

# int8
quantization_config = BitsAndBytesConfig(load_in_8bit=True)

pipeline_ins = pipeline(
            task=Tasks.text_generation, model='qwen/Qwen-7B', device_map='auto', quantization_config=quantization_config)
text = '蒙古国的首都是乌兰巴托（Ulaanbaatar）\n冰岛的首都是雷克雅未克（Reykjavik）\n埃塞俄比亚的首都是'
result = pipeline_ins(text)
print(result['text'])
```
报错

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/large/npuheart9/.local/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 119, in pipeline
    check_config(cfg)
  File "/home/large/npuheart9/.local/lib/python3.10/site-packages/modelscope/utils/config.py", line 670, in check_config
    check_attr(ConfigFields.pipeline)
  File "/home/large/npuheart9/.local/lib/python3.10/site-packages/modelscope/utils/config.py", line 665, in check_attr
    assert hasattr(cfg, attr_name), f'Attribute {attr_name} is missing from ' \
AssertionError: Attribute pipeline is missing from configuration.json. 
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by Lukeming-tsinghua** [comment]
您好，感谢反馈！

当前版本的 Qwen 的 modelscope pipeline 暂时仍在开发中，预计很快就会合并至 modelscope lib。
