### ISSUE TITLE
[BUG] <tiktoken能替换为llamatoken吗？>

### ISSUE THREAD

**Issue by Romaosir** [QwenLM/Qwen#264]
如题，tiktoken在部署任务中并不通用，比如text-generation-inference官方镜像并不支持tiktoken

**Comment by jklj077** [comment]
1. llamatoken是指sentencepiece吗？sentencepiece的处理逻辑跟Qwen用的tiktoken不同，无法替换。
2. 如果有部署需求，那么从性能角度来看tiktoken是目前开源tokenizer中效率最高的。
3. 第三方库的支持问题，建议寻求第三方维护人员解决。我们不清楚TGI的具体问题是什么、是不是还有其它坑，TGI中有相关issue：huggingface/text-generation-inference#779 
   如果只是缺包的话，可以将text-generation-inference的官方镜像作为base，再安装一下tiktoken就好，docker镜像还是很好改的，仅供参考。

**Comment by jklj077** [comment]
1. llamatoken是指sentencepiece吗？sentencepiece的处理逻辑跟Qwen用的tiktoken不同，无法替换。
2. 如果有部署需求，那么从性能角度来看tiktoken是目前开源tokenizer中效率最高的。
3. 第三方库的支持问题，建议寻求第三方维护人员解决。我们不清楚TGI的具体问题是什么、是不是还有其它坑，TGI中有相关issue：huggingface/text-generation-inference#779 
   如果只是缺包的话，可以将text-generation-inference的官方镜像作为base，再安装一下tiktoken就好，docker镜像还是很好改的，仅供参考。

**Comment by Romaosir** [comment]
> 1. llamatoken是指sentencepiece吗？sentencepiece的处理逻辑跟Qwen用的tiktoken不同，无法替换。
> 2. 如果有需求需求，那么从性能角度来看tiktoken是目前开源tokenizer中效率最高的。
> 3. 库的支持问题，建议寻求第三方维护人员解决。我们蜡烛TGI的具体问题是什么、不是还有其他坑，TGI有相关问题：Qwen-7B支持huggingface/text- Generation- [inference ](https://github.com/huggingface/text-generation-inference/issues/779)[ # 779](https://github.com/huggingface/text-generation-inference/issues/779)
>    如果只是缺包的话，可以将text- Generation-inference的官方镜像作为基础，再安装一下tiktoken就可以了，docker镜像还是很好改的，仅供参考。[](https://github.com/huggingface/text-generation-inference/issues/779)

感谢解答！
这是我最新的探索：tiktoken+transformers-stream-generator，可以更新TGI镜像解决。
最新遇到的问题：TGI不支持AutoModel（config中的model_type字段）的分片部署，源码见：https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/__init__.py。

**Comment by paulcx** [comment]
> > 1. llamatoken是指sentencepiece吗？sentencepiece的处理逻辑跟Qwen用的tiktoken不同，无法替换。
> > 2. 如果有需求需求，那么从性能角度来看tiktoken是目前开源tokenizer中效率最高的。
> > 3. 库的支持问题，建议寻求第三方维护人员解决。我们蜡烛TGI的具体问题是什么、不是还有其他坑，TGI有相关问题：Qwen-7B支持huggingface/text- Generation- [inference ](https://github.com/huggingface/text-generation-inference/issues/779)[ # 779](https://github.com/huggingface/text-generation-inference/issues/779)
> >    如果只是缺包的话，可以将text- Generation-inference的官方镜像作为基础，再安装一下tiktoken就可以了，docker镜像还是很好改的，仅供参考。
> 
> 感谢解答！ 这是我最新的探索：tiktoken+transformers-stream-generator，可以更新TGI镜像解决。 最新遇到的问题：TGI不支持AutoModel（config中的model_type字段）的分片部署，源码见：[https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/__init__.py。](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/__init__.py%E3%80%82)

问题解决了吗？

**Comment by jklj077** [comment]
> 最新遇到的问题：TGI不支持AutoModel（config中的model_type字段）的分片部署

这个就没什么办法了，看TGI什么时候能支持这些模型了。看了下代码，那几个单独写的Sharded模型代码还是比较像的。TGI的支持问题，请寻求TGI的帮助，safetensors也是huggingface自己的东西了。本issue就先关闭了。

另外，FastChat最近完善了对Qwen的支持，我们也提供了vllm部署的说明，可以看README的Deployment部分<https://github.com/QwenLM/Qwen#vllm>，有可能的话，可以尝试看看。

**Comment by BrightXiaoHan** [comment]
TGI部署时遇到这个错误
```
2024-01-05T11:20:53.653089Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 370, in get_model
    return CausalLM(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 528, in __init__
    tokenizer.add_special_tokens({"pad_token": "[PAD]"})
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 971, in add_special_tokens
    added_tokens = self.add_tokens(added_tokens, special_tokens=True)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1021, in add_tokens
    return self._add_tokens(new_tokens, special_tokens=special_tokens)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/tokenization_qwen.py", line 165, in _add_tokens
    raise ValueError("Adding unknown special tokens is not supported")
ValueError: Adding unknown special tokens is not supported

2024-01-05T11:20:54.449399Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  4.56it/s]
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 370, in get_model
    return CausalLM(

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 528, in __init__
    tokenizer.add_special_tokens({"pad_token": "[PAD]"})

  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 971, in add_special_tokens
    added_tokens = self.add_tokens(added_tokens, special_tokens=True)

  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1021, in add_tokens
    return self._add_tokens(new_tokens, special_tokens=special_tokens)

  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat/tokenization_qwen.py", line 165, in _add_tokens
    raise ValueError("Adding unknown special tokens is not supported")

ValueError: Adding unknown special tokens is not supported
 rank=0
```
