### ISSUE TITLE
使用4bit gptq权重进行微调出现错误

### ISSUE THREAD

**Issue by felixstander** [QwenLM/Qwen#307]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用了官方已经量化好的auto-gptq 4bit模型进行微调时，出现了optimum包相关的报错。
File "finetune.py", line 295, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/optimum/gptq/quantizer.py", line 306, in quantize_model
    raise ValueError("You need to pass `dataset` in order to quantize your model")
ValueError: You need to pass `dataset` in order to quantize your model

### 期望行为 | Expected Behavior

按道理这里已经量化好的模型是不需要传入dataset进行量化的，为何这里还是会出现相关的报错?

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04.
- Python:3.8
- Transformers:4.32.0
- PyTorch:2.0.0+cu118
- Optimum:1.14.0.dev0
- CUDA 11.8
```

**Comment by JustinLin610** [comment]
运行的是哪个脚本？提供下更完整的运行记录？

**Comment by felixstander** [comment]
运行的是官方的finetune.py的脚本。
更具体地报错如下:
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "finetune.py", line 355, in <module>
    train()
  File "finetune.py", line 295, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3283, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/optimum/gptq/quantizer.py", line 306, in quantize_model
    raise ValueError("You need to pass `dataset` in order to quantize your model")
ValueError: You need to pass `dataset` in order to quantize your model

ps:
相同的环境跑peft官方的finetune_llama_gptq.py脚本是没有问题的。

**Comment by 5466566** [comment]
> eft官方的

那你是再怎么解决这个问题的，我也遇到了
