### ISSUE TITLE
微调运行sh finetune/finetune_ds.sh 报错

### ISSUE THREAD

**Issue by SilenceWinter** [QwenLM/Qwen#315]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我希望做全量微调（8卡A100应该可以吧），所以运行sh finetune/finetune_ds.sh

以下是运行脚本：
```
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

GPUS_PER_NODE=8
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="/home/xxxx/llm_model/qwen-7b-chat" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="/home/xxxx/pyproj/Qwen-7B/finetune/dummy_data2.json"

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --bf16 True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "none" \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --deepspeed finetune/ds_config_zero3.json
```

报错信息：

```
: not foundfinetune_ds.sh: 4: 
: not foundfinetune_ds.sh: 10: 
: not foundfinetune_ds.sh: 15: 
: not foundfinetune_ds.sh: 23: 
': [Errno 2] No such file or directory/bin/python: can't open file '/home/xxxx/pyproj/Qwen-7B/
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1102994) of binary: /home/xxxx/miniconda3/envs/firefly39/bin/python
Traceback (most recent call last):
  File "/home/xxxx/miniconda3/envs/firefly39/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/xxxx/miniconda3/envs/firefly39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xxxx/miniconda3/envs/firefly39/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/xxxx/miniconda3/envs/firefly39/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/xxxx/miniconda3/envs/firefly39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxxx/miniconda3/envs/firefly39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
 FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-22_17:48:59
  host      : xxxx-SSxxxxMBX-XI6-E711
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 1102994)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
./finetune/finetune_ds.sh: 25: --model_name_or_path: not found
./finetune/finetune_ds.sh: 26: --data_path: not found
./finetune/finetune_ds.sh: 27: --bf16: not found
./finetune/finetune_ds.sh: 28: --output_dir: not found
./finetune/finetune_ds.sh: 29: --num_train_epochs: not found
./finetune/finetune_ds.sh: 30: --per_device_train_batch_size: not found
./finetune/finetune_ds.sh: 31: --per_device_eval_batch_size: not found
./finetune/finetune_ds.sh: 32: --gradient_accumulation_steps: not found
./finetune/finetune_ds.sh: 33: --evaluation_strategy: not found
./finetune/finetune_ds.sh: 34: --save_strategy: not found
./finetune/finetune_ds.sh: 35: --save_steps: not found
./finetune/finetune_ds.sh: 36: --save_total_limit: not found
./finetune/finetune_ds.sh: 37: --learning_rate: not found
./finetune/finetune_ds.sh: 38: --weight_decay: not found
./finetune/finetune_ds.sh: 39: --adam_beta2: not found
./finetune/finetune_ds.sh: 40: --warmup_ratio: not found
./finetune/finetune_ds.sh: 41: --lr_scheduler_type: not found
./finetune/finetune_ds.sh: 42: --logging_steps: not found
./finetune/finetune_ds.sh: 43: --report_to: not found
./finetune/finetune_ds.sh: 44: --model_max_length: not found
./finetune/finetune_ds.sh: 45: --gradient_checkpointing: not found
./finetune/finetune_ds.sh: 46: --lazy_preprocess: not found
./finetune/finetune_ds.sh: 47: --deepspeed: not found
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by BoyaWu10** [comment]
I've encountered the same problem and I solved it by changing `CRLF` in `finetune_ds.sh` is with `LF`.

**Comment by hnlp1993** [comment]
bash finetune_ds.sh 试试

**Comment by jklj077** [comment]
前面comments有提到，linux下的shell不认`\r\n`，会报类似的错误。finetune_ds.sh里原本都是`\n`的，建议检查看看。
