### ISSUE TITLE
[BUG] Failed to launch `sh finetune/finetune_qlora_ds.sh` with error: ImportError: This modeling file requires the following packages that were not found in your environment: kernels. Run `pip install kernels`

### ISSUE THREAD

**Issue by jinqiupeter** [QwenLM/Qwen#347]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Got an error when running `sh pip install environment-kernels`, full log:
```
sh finetune/finetune_qlora_ds.sh
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-09-26 00:04:17,229] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-26 00:04:17,236] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-26 00:04:18,250] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-26 00:04:18,254] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-09-26 00:04:18,254] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "/media/peter/Data/Qwen/finetune.py", line 353, in <module>
    train()
  File "/media/peter/Data/Qwen/finetune.py", line 294, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: kernels. Run `pip install kernels`
Traceback (most recent call last):
  File "/media/peter/Data/Qwen/finetune.py", line 353, in <module>
    train()
  File "/media/peter/Data/Qwen/finetune.py", line 294, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/peter/.local/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: kernels. Run `pip install kernels`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 107288) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/peter/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/peter/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/peter/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/peter/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/peter/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/peter/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-26_00:04:26
  host      : peter-ubuntu1
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 107289)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-26_00:04:26
  host      : peter-ubuntu1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 107288)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
``` 

**Environment: Ubuntu 2204, nvidia-smi:**

```
nvidia-smi
Tue Sep 26 00:06:56 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:01:00.0 Off |                  N/A |
| 60%   52C    P8              48W / 370W |    690MiB / 24576MiB |      6%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        On  | 00000000:05:00.0  On |                  N/A |
|  0%   49C    P8              36W / 370W |    100MiB / 24576MiB |     26%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

``` 

My finetune_qlora_ds.sh config:
```
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

GPUS_PER_NODE=2
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="Qwen/Qwen-14B-Chat-Int4" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="data/gptea_zh_qwen.json"

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"

# Remember to use --fp16 instead of --bf16 due to autogptq
torchrun $DISTRIBUTED_ARGS finetune.py \
    --model_name_or_path $MODEL \
    --data_path $DATA \
    --fp16 True \
    --output_dir output_qwen \
    --num_train_epochs 5 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "no" \
    --learning_rate 1e-5 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --report_to "wandb" \
    --model_max_length 512 \
    --lazy_preprocess True \
    --use_lora \
    --q_lora \
    --gradient_checkpointing \
    --deepspeed finetune/ds_config_zero2.json

``` 

### 期望行为 | Expected Behavior

sh finetune/finetune_qlora_ds.sh can run without error.

### 复现方法 | Steps To Reproduce

1. git clone the repo
2. run pip install -r requirements.txt
3. run pip install deepspeed peft wandb
4. configure finetune/finetune_qlora_ds.sh and run
5. got the error
6. run pip install auto-gptq optimum
7. still got the error 

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python: 3.10.12
- Transformers:4.32.0
- PyTorch: 2.0.1+cu117
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

### 备注 | Anything else?

Google has not similar cases

**Comment by jinqiupeter** [comment]
Same issue as https://github.com/QwenLM/Qwen/issues/345 , closing this one
