### ISSUE TITLE
[BUG] open_ai 回答报错

### ISSUE THREAD

**Issue by airclear** [QwenLM/Qwen#396]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

model: Qwen/Qwen-14B-Chat-Int4

使用open_ai 启动，调用api的过程报如下错误：
使用cli 和 webui 都不报错

```
INFO:     Started server process [9960]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.10.110:61537 - "CONNECT fonts.googleapis.com%3A443 HTTP/1.0" 404 Not Found
INFO:     192.168.10.110:60701 - "OPTIONS /v1/chat/completions HTTP/1.1" 200 OK
INFO:     192.168.10.110:60701 - "POST /v1/chat/completions HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\sse_starlette\sse.py", line 247, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\sse_starlette\sse.py", line 236, in wrap
    await func()
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\sse_starlette\sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "D:\works\demos\Qwen\openai_api.py", line 432, in predict
    for new_response in response_generator:
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\f91fa8d7b06d37b8f539e57ef48b17ac05012f7f\modeling_qwen.py", line 1273, in stream_generator
    for token in self.generate_stream(
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "C:\ProgramData\Anaconda3\envs\baichuan\lib\site-packages\transformers_stream_generator\main.py", line 969, in sample_stream
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

### 期望行为 | Expected Behavior

正常回答不要报错

### 运行环境 | Environment

```Markdown
- OS: Windows 10
- Python: 3.9 
- Transformers:  4.32.0
- PyTorch: 2.0.0+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

**Comment by JustinLin610** [comment]
请问是不是调了temperature？

**Comment by airclear** [comment]
> 请问是不是调了temperature？

除了更改模型，其他代码没动过

**Comment by allenhaozi** [comment]
same error encountered

```sh
python openai_api.py -c /home/work/Qwen-14B-Chat-Int4
```

```
INFO:     10.100.116.41:52381 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "openai_api.py", line 395, in create_chat_completion
    response, _ = model.chat(
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-Int4/modeling_qwen.py", line 1195, in chat
    outputs = self.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat-Int4/modeling_qwen.py", line 1314, in generate
    return super().generate(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2760, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by allenhaozi** [comment]
> > 请问是不是调了temperature？
> 
> 除了更改模型，其他代码没动过

Has the problem been solved?

**Comment by mikeleatila** [comment]
@allenhaozi @airclear @JustinLin610 @hzhwcmhf I am using Qwen-14B-Chat-Int4 and in the inference I am also getting: "RuntimeError: probability tensor contains either `inf`, `nan` or element < 0" Has this been fixed and how? Many thanks

**Comment by jklj077** [comment]
Hi, guys, currently the Int4 quantized models cannot be used with low temperature and low top_p values. Please try using temperature = 1 and top_p > 0.5 (e.g., 0.8). 

If the problem still exists, it would be better if you could provide a MWE for us to reproduce the issue. Thanks in advance.

**Comment by chenhaoqiang** [comment]
> Hi, guys, currently the Int4 quantized models cannot be used with low temperature and low top_p values. Please try using temperature = 1 and top_p > 0.5 (e.g., 0.8). 
> 
> 
> 
> If the problem still exists, it would be better if you could provide a MWE for us to reproduce the issue. Thanks in advance.

@jklj077 您好，我也遇到了这个问题，因为基于知识库问答，我想要模型回答的严谨，当temperature设置成0.01时，推理报Internal Server Error
