### ISSUE TITLE
[BUG] 微调报错

### ISSUE THREAD

**Issue by dreamagician** [QwenLM/Qwen#397]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
[2023-10-06 12:02:18,519] torch.distributed.run: [WARNING] 
[2023-10-06 12:02:18,519] torch.distributed.run: [WARNING] *****************************************
[2023-10-06 12:02:18,519] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-10-06 12:02:18,519] torch.distributed.run: [WARNING] *****************************************
[2023-10-06 12:02:19,462] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-06 12:02:19,464] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-06 12:02:20,034] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-06 12:02:20,035] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-10-06 12:02:20,035] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
[2023-10-06 12:02:37,677] [INFO] [partition_parameters.py:347:__exit__] finished initializing model - num_params = 259, num_elems = 7.72B

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
Loading checkpoint shards:  12%|█▎        | 1/8 [00:05<00:41,  5.99s/it]
Loading checkpoint shards:  12%|█▎        | 1/8 [00:06<00:45,  6.57s/it]
Loading checkpoint shards:  25%|██▌       | 2/8 [00:10<00:32,  5.39s/it]
Loading checkpoint shards:  25%|██▌       | 2/8 [00:11<00:33,  5.63s/it]
Loading checkpoint shards:  38%|███▊      | 3/8 [00:15<00:25,  5.20s/it]
Loading checkpoint shards:  38%|███▊      | 3/8 [00:16<00:26,  5.32s/it]
Loading checkpoint shards:  50%|█████     | 4/8 [00:20<00:20,  5.10s/it]
Loading checkpoint shards:  50%|█████     | 4/8 [00:21<00:20,  5.18s/it]
Loading checkpoint shards:  62%|██████▎   | 5/8 [00:25<00:15,  5.05s/it]
Loading checkpoint shards:  62%|██████▎   | 5/8 [00:26<00:15,  5.10s/it]
Loading checkpoint shards:  75%|███████▌  | 6/8 [00:30<00:10,  5.02s/it]
Loading checkpoint shards:  75%|███████▌  | 6/8 [00:31<00:10,  5.05s/it]
Loading checkpoint shards:  88%|████████▊ | 7/8 [00:35<00:04,  5.00s/it]
Loading checkpoint shards: 100%|██████████| 8/8 [00:35<00:00,  4.48s/it]

Loading checkpoint shards:  88%|████████▊ | 7/8 [00:36<00:05,  5.02s/it]
Loading checkpoint shards: 100%|██████████| 8/8 [00:38<00:00,  4.00s/it]
Loading checkpoint shards: 100%|██████████| 8/8 [00:38<00:00,  4.77s/it]
Loading data...
Formatting inputs...Skip in lazy mode
Using /home/username/.cache/torch_extensions/py311_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/username/.cache/torch_extensions/py311_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.032184600830078125 seconds
/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/ops/adam/fused_adam.py:96: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = get_accelerator().IntTensor([0])
Parameter Offload: Total persistent parameters: 659456 in 99 params
Using /home/username/.cache/torch_extensions/py311_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/username/.cache/torch_extensions/py311_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.031077861785888672 seconds
/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/ops/adam/fused_adam.py:96: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = get_accelerator().IntTensor([0])

  0%|          | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/hdd1/artificial-intelligence/apps/Qwen/finetune.py", line 353, in <module>
    train()
  File "/mnt/hdd1/artificial-intelligence/apps/Qwen/finetune.py", line 346, in train
    trainer.train()
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 2682, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 2707, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1801, in forward
    loss = self.module(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
Traceback (most recent call last):
  File "/mnt/hdd1/artificial-intelligence/apps/Qwen/finetune.py", line 353, in <module>
    return self._call_impl(*args, **kwargs)
           ^^^^^^    ^train()^
^^^^^^^^^^^^^^^^  File "/mnt/hdd1/artificial-intelligence/apps/Qwen/finetune.py", line 346, in train
^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    trainer.train()
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/peft/peft_model.py", line 918, in forward
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    tr_loss_step = self.training_step(model, inputs)    
return self._call_impl(*args, **kwargs)
           ^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 2682, in training_step
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^loss = self.compute_loss(model, inputs)^
^^
  File "/home/username/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1108, in forward
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/transformers/trainer.py", line 2707, in compute_loss
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
    return self._call_impl(*args, **kwargs)  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^    ^result = forward_call(*args, **kwargs)^
^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 866, in forward
    return forward_call(*args, **kwargs)
           ^^^^^^^    ^inputs_embeds = self.wte(input_ids)^
^^^^^^^^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ 
    File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
       ^^^^^^    ^ret_val = func(*args, **kwargs)^
^^^^^^^ ^ ^ ^ ^ 
    File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 1801, in forward
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    loss = self.module(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/peft/utils/other.py", line 186, in forward
    return self._call_impl(*args, **kwargs)
        return self.modules_to_save[self.active_adapter](*args, **kwargs) 
      ^^^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/peft/peft_model.py", line 918, in forward
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1557, in _call_impl
    return self.base_model(
           ^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    args_result = hook(self, args)
                  ^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    return self._call_impl(*args, **kwargs)
    ret_val = func(*args, **kwargs)
                   ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 392, in _pre_forward_module_hook
^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    self.pre_sub_module_forward_function(module)
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 505, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module, forward=prev_grad_state)
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    result = forward_call(*args, **kwargs)
    ret_val = func(*args, **kwargs)
                       ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return func(*args, **kwargs)
    return self.model.forward(*args, **kwargs)
                 ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 310, in fetch_sub_module
^^^^^^^^^^^^^^^^^
  File "/home/username/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1108, in forward
    assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'id': 259, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}
    transformer_outputs = self.transformer(
                          ^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 866, in forward
    inputs_embeds = self.wte(input_ids)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/peft/utils/other.py", line 186, in forward
    return self.modules_to_save[self.active_adapter](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1557, in _call_impl
    args_result = hook(self, args)
                  ^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 392, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 505, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module, forward=prev_grad_state)
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 310, in fetch_sub_module
    assert param.ds_status == ZeroParamStatus.AVAILABLE, param.ds_summary()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: {'id': 259, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0,), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {7}, 'ds_tensor.shape': torch.Size([0])}

  0%|          | 0/5 [00:00<?, ?it/s]
[2023-10-06 12:03:58,524] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 12352) of binary: /home/username/anaconda3/envs/Qwen/bin/python
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/Qwen/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/anaconda3/envs/Qwen/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-10-06_12:03:58
  host      : username-workstation
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 12353)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-06_12:03:58
  host      : username-workstation
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12352)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 22.04
- Python: 3.11.5
- Transformers: 4.32.0
- PyTorch: 2.1.0+cu121
- CUDA 12.1
```

**Comment by JustinLin610** [comment]
具体使用的是哪个脚本？

**Comment by faship** [comment]
我也遇到了，好像跟用了deepspeed offload_device='cpu'有关系

**Comment by Mathsion2** [comment]
解决了吗，我也碰到了!!!

**Comment by dreamagician** [comment]
> 具体使用的是哪个脚本？

finetune_lora_ds.sh
ds_config_zero3.json

**Comment by Dagoli** [comment]
> ```python
> modules_to_save
> ```

没解决啊 还是有这个问题

**Comment by Dagoli** [comment]
@dreamagician

**Comment by cat-sun** [comment]
请问解决了吗，我也遇到了这个问题 @Dagoli
