### ISSUE TITLE
[BUG] < event_id Field required>

### ISSUE THREAD

**Issue by flowbywind** [QwenLM/Qwen#417]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用web_demo.py运行 提示event_id field required 

Task exception was never retrieved
future: <Task finished name='ubtr7s97k5_1' coro=<Queue.process_events() done, defined at /usr/local/anaconda3/envs/qwen/lib/python3.9/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 1, 'data': [...ion_hash': 'ubtr7s97k5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing>
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/qwen/lib/python3.9/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/anaconda3/envs/qwen/lib/python3.9/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/anaconda3/envs/qwen/lib/python3.9/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/anaconda3/envs/qwen/lib/python3.9/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 1, 'data': [...ion_hash': 'ubtr7s97k5'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

### 期望行为 | Expected Behavior

正常运行

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by flowbywind** [comment]
the issure is because pydantic  version. error version is  2.4.1 
the solove function is uninstall pydantic and install pydantic== 1.10.7
