### ISSUE TITLE
使用v100、fp16、lora微调，报错

### ISSUE THREAD

**Issue by situjunhao** [QwenLM/Qwen#418]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.81it/s]
Loading data...
Formatting inputs...Skip in lazy mode
  0%|                                                                                                           | 0/25410 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (1507 > 512). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/mnt/workspace/Qwen/finetune.py", line 362, in <module>
    train()
  File "/mnt/workspace/Qwen/finetune.py", line 355, in train
    trainer.train()
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/transformers/trainer.py", line 1895, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/accelerate/accelerator.py", line 2120, in clip_grad_norm_
    self.unscale_gradients()
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/accelerate/accelerator.py", line 2083, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/llm/lib/python3.11/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

### 期望行为 | Expected Behavior

正常启动

### 复现方法 | Steps To Reproduce

使用v100，fp16，single_gpu，lora进行微调

### 运行环境 | Environment

```Markdown
- OS:ubuntu18.04
- Python:3.11
- Transformers:4.32.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
```

**Comment by JustinLin610** [comment]
oh 如果走fp16，不走bf16，需要修改下脚本走deepspeed（已经在更新的脚本中给出），pytorch的amp会有这个报错

**Comment by Mary2333** [comment]
嗨，我也遇到了同样的报错，我是通过把peft的版本降低为0.4.0解决的，你可以试一下。peft=0.7.1的时候会报错。
