### ISSUE TITLE
[BUG] 单卡Qlora微调qwen-14b-chat-int4报错

### ISSUE THREAD

**Issue by dijkstra-mose** [QwenLM/Qwen#499]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
$ bash finetune_qlora_single_gpu.sh 
[2023-10-19 18:26:45,801] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loa
ding attributes (e.g. disable_exllama, use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经
开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Try importing flash-attention for faster inference...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  2.90it/s]
Loading data...
Formatting inputs...Skip in lazy mode
Using /home/work/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Creating extension directory /home/work/.cache/torch_extensions/py310_cu117/fused_adam...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/work/.cache/torch_extensions/py310_cu117/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda-11.7/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBI
ND11_BUILD_ABI=\"_cxxabi1011\" -I/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/work/anaconda3/envs/qwen/lib/python3.10/sit
e-packages/deepspeed/ops/csrc/adam -isystem /home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/include -isystem /home/work/anaconda3/envs/qwen/lib/python3.10
/site-packages/torch/include/torch/csrc/api/include -isystem /home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/include/TH -isystem /home/work/anaconda3/envs
/qwen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/include -isystem /home/work/anaconda3/envs/qwen/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI
=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_8
6,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=
compute_86,code=sm_86 -gencode=arch=compute_86,code=compute_86 -DBF16_AVAILABLE -std=c++17 -c /home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/deepspeed/ops/csrc/a
dam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
[2/3] c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" 
-DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/work/anaconda3/envs/qwen/lib/python3.
10/site-packages/deepspeed/ops/csrc/adam -isystem /home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/include -isystem /home/work/anaconda3/envs/qwen/lib/pyth
on3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/include/TH -isystem /home/work/anaconda
3/envs/qwen/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda-11.7/include -isystem /home/work/anaconda3/envs/qwen/include/python3.10 -D_GLIBCXX_USE_CXX
11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DBF16_AVAILABLE -c /home/work/anaconda3/envs/qwen/lib/python3.10/
site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
[3/3] c++ fused_adam_frontend.o multi_tensor_adam.cuda.o -shared -L/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_
cuda -ltorch -ltorch_python -L/usr/local/cuda-11.7/lib64 -lcudart -o fused_adam.so
Loading extension module fused_adam...
Time to load fused_adam op: 11.578975677490234 seconds
  0%|
Traceback (most recent call last):
  File "/home/work/workspace/med-gpt/trainer/qwen/finetune.py", line 364, in <module>
    train()
  File "/home/work/workspace/med-gpt/trainer/qwen/finetune.py", line 357, in train
    trainer.train()
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 2682, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 2707, in compute_loss
    outputs = model(**inputs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1807, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/peft/peft_model.py", line 918, in forward
    return self.base_model(
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 94, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-int4/modeling_qwen.py", line 1109, in forward
    transformer_outputs = self.transformer(
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-int4/modeling_qwen.py", line 918, in forward
    outputs = torch.utils.checkpoint.checkpoint(
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/work/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-int4/modeling_qwen.py", line 914, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-int4/modeling_qwen.py", line 631, in forward
    attn_outputs = self.attn(
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
   return forward_call(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-int4/modeling_qwen.py", line 538, in forward
    context_layer = self.core_attention_flash(q, k, v, attention_mask=attention_mask)
  File "/home/work/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-int4/modeling_qwen.py", line 209, in forward
    assert seqlen_k == seqlen_q
AssertionError
  0%|             
```

### 复现方法 | Steps To Reproduce

finetune_qlora_single_gpu.sh

```
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`
MODEL="/home/work/workspace/qwen/qwen-14b/qwen-14b-chat-int4"
DATA=......
OUTPUT=......
source ~/anaconda3/bin/activate qwen
export CUDA_VISIBLE_DEVICES=0

# Remember to use --fp16 instead of --bf16 due to autogptq
python finetune.py \
  --model_name_or_path $MODEL \
  --data_path $DATA \
  --fp16 True \
  --output_dir $OUTPUT \
  --num_train_epochs 5 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 1000 \
  --save_total_limit 10 \
  --learning_rate 3e-4 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --report_to "none" \
  --model_max_length 512 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora \
  --q_lora \
  --deepspeed finetune/ds_config_zero2.json
```

### 运行环境 | Environment

```Markdown
- OS: Ubuntu22.04
- Python:3.10.9
- Transformers:4.32.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
```

**Comment by JustinLin610** [comment]
没遇到过 有更多信息可以帮助复现吗？

**Comment by dijkstra-mose** [comment]
怀疑是python库环境的问题。用另一个微调项目可以跑的。

**Comment by jklj077** [comment]
Hi, which auto_gptq version did you use? Could you please try if using the latest code and updating auto_gptq could resolve the problem?
