### ISSUE TITLE
[BUG] T4单卡QLoRA微调7B int4模型报错

### ISSUE THREAD

**Issue by zjmvwb1** [QwenLM/Qwen#502]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我在用T4单卡跑7B int4的QLoRA微调，跑不了，显示内存溢出。报错信息如下：
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.22it/s]
Loading data...
Formatting inputs...Skip in lazy mode
  0%|                                                                                                                                                                                        | 0/5 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (12 > 10). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/opt/push/llm_models/Qwen/finetune/finetune.py", line 353, in <module>
    train()
  File "/opt/push/llm_models/Qwen/finetune/finetune.py", line 346, in train
    trainer.train()
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self.optimizer.step()
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/accelerate/optimizer.py", line 145, in step
    self.optimizer.step(closure)
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/torch/optim/adamw.py", line 160, in step
    self._init_group(
  File "/opt/push/anaconda3/envs/llm_qwen/lib/python3.10/site-packages/torch/optim/adamw.py", line 118, in _init_group
    state["exp_avg_sq"] = torch.zeros_like(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 14.76 GiB total capacity; 14.05 GiB already allocated; 3.75 MiB free; 14.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                                                                                                                        | 0/5 [00:04<?, ?it/s]

### 期望行为 | Expected Behavior

理论上说，7B的int4量化后占用内存很小，QLoRA也降低了很大的显存占用，按理来说不会有内存溢出的问题，就很奇怪。我只是拿10条数据，想跑通QLoRA微调流程而已。

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
README中有相关统计 https://github.com/QwenLM/Qwen#profiling-of-memory-and-speed

![image](https://github.com/QwenLM/Qwen/assets/17811943/51e43cee-7a99-4e15-a977-1562a215c5f9)

但开了flash_attention，可以节省一些显存。而且看log是在最后更新参数的时候显存不够了（前向、反向都算完了），可能确实是比较极限。

**Comment by JustinLin610** [comment]
T4 16GB显存如果不是特别长的就按上面这个数字来参考，加上flash attn，也看下是不是只有这个模型训练占用显存吧
