### ISSUE TITLE
[BUG] 安装 flash-attn 后调用量化后的模型推理报错：FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat

### ISSUE THREAD

**Issue by edisonwd** [QwenLM/Qwen#506]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1、加载量化模型成功
2、调用model.generate生成结果报错
3、报错信息如下：
```
Traceback (most recent call last):
  File "generation_speed.py", line 343, in <module>
    main()
  File "generation_speed.py", line 335, in main
    benchmark_generation_speed(model, tokenizer, examples, generation_config)
  File "generation_speed.py", line 209, in benchmark_generation_speed
    outputs_ids = model.generate(
  File "/opt/conda/lib/python3.8/site-packages/auto_gptq/modeling/_base.py", line 443, in generate
    return self.model.generate(**kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1330, in generate
    return super().generate(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py", line 2724, in sample
    outputs = self(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1120, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 950, in forward
    outputs = block(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 670, in forward
    layernorm_output = self.ln_2(layernorm_input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1425, in forward
    return rms_norm(x, self.weight, self.eps)
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/ops/rms_norm.py", line 15, in rms_norm
    return DropoutAddLayerNormFn.apply(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/ops/layer_norm.py", line 334, in forward
    zmat, xmat, dmask, mu, rsigma = _dropout_add_layer_norm_forward(
  File "/opt/conda/lib/python3.8/site-packages/flash_attn/ops/layer_norm.py", line 33, in _dropout_add_layer_norm_forward
    zmat, xmat, dmask, mu, rsigma = dropout_layer_norm.dropout_add_ln_fwd(
RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
```

### 期望行为 | Expected Behavior

量化模型能够正常推理

### 复现方法 | Steps To Reproduce

1、使用下面的代码加载量化模型
```python
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

from transformers import AutoTokenizer, GenerationConfig

quantized_model_dir = 'Qwen-14B-4bit-GPTQ/'

tokenizer = AutoTokenizer.from_pretrained(quantized_model_dir,
                                          use_fast=True,
                                          trust_remote_code=True)

model = AutoGPTQForCausalLM.from_quantized(quantized_model_dir,  
                                           device_map="auto", 
                                           use_safetensors=True, 
                                           trust_remote_code=True)

print(tokenizer)
print(model)

```
输出结果如下：
```python

QWenTokenizer(name_or_path='Qwen-14B-4bit-GPTQ/', vocab_size=159729, model_max_length=8192, is_fast=False, padding_side='left', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<|endoftext|>']}, clean_up_tokenization_spaces=True)
QwenGPTQForCausalLM(
  (model): QWenLMHeadModel(
    (transformer): QWenModel(
      (wte): Embedding(159729, 5120)
      (drop): Dropout(p=0.0, inplace=False)
      (rotary_emb): RotaryEmbedding()
      (h): ModuleList(
        (0-39): 40 x QWenBlock(
          (ln_1): RMSNorm()
          (attn): QWenAttention(
            (core_attention_flash): FlashSelfAttention()
            (attn_dropout): Dropout(p=0.0, inplace=False)
            (c_attn): GeneralQuantLinear(in_features=5120, out_features=15360, bias=True)
            (c_proj): GeneralQuantLinear(in_features=5120, out_features=5120, bias=True)
          )
          (ln_2): RMSNorm()
          (mlp): QWenMLP(
            (c_proj): GeneralQuantLinear(in_features=13696, out_features=5120, bias=True)
            (w1): GeneralQuantLinear(in_features=5120, out_features=13696, bias=True)
            (w2): GeneralQuantLinear(in_features=5120, out_features=13696, bias=True)
          )
        )
      )
      (ln_f): RMSNorm()
    )
    (lm_head): Linear(in_features=5120, out_features=159729, bias=False)
  )
)
```
2、使用下面的代码调用模型推理
```python
print(tokenizer.decode(model.generate(**tokenizer("你是谁", return_tensors="pt").to(model.device))[0]))
```

3、报错信息如下

```python
RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
```
详细的报错信息在上面已经贴出来了

### 运行环境 | Environment

```Markdown
- OS: Linux
- Python 3.8.16
- transformers==4.32.0
- torch==2.0.1
- CUDA Version: 11.7
```

**Comment by JustinLin610** [comment]
确定是拉的我们提供的Int4模型？为什么不用我们给的用法直接测要用原来的AutoGPTQ的用法

**Comment by edisonwd** [comment]
> 确定是拉的我们提供的Int4模型？为什么不用我们给的用法直接测要用原来的AutoGPTQ的用法

因为我们自己基于Qwen-14B进行训练，然后自己使用AutoGPTQ 进行了量化，所以遇到这个问题，请问一下你们提供的int模型是怎么量化的，有相关文档参考一下吗

**Comment by hannlp** [comment]
同遇到这个问题， @edisonwd @JustinLin610 麻烦问一下有进展吗

**Comment by edisonwd** [comment]
> 同遇到这个问题， @edisonwd @JustinLin610 麻烦问一下有进展吗

卸载flash-attn，就可以正常推理
