### ISSUE TITLE
[BUG] <title>lora 训练后，想合并权重到原模型，发现不能成功。

### ISSUE THREAD

**Issue by staticTao** [QwenLM/Qwen#512]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [x] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

合并代码如下。

```python
import torch
from peft import PeftModel
from transformers import AutoTokenizer, AutoModelForCausalLM, LlamaTokenizer


def apply_lora(model_name_or_path, output_path, lora_path):
    print(f"Loading the base model from {model_name_or_path}")
    base = AutoModelForCausalLM.from_pretrained(
        model_name_or_path, torch_dtype=torch.float16, low_cpu_mem_usage=True
    )
    base_tokenizer = LlamaTokenizer.from_pretrained(model_name_or_path)

    print(f"Loading the LoRA adapter from {lora_path}")

    lora_model = PeftModel.from_pretrained(
        base,
        lora_path,
        torch_dtype=torch.float16,
    )

    print("Applying the LoRA")
    model = lora_model.merge_and_unload()

    print(f"Saving the target model to {output_path}")
    model.save_pretrained(output_path)
    base_tokenizer.save_pretrained(output_path)


if __name__ == "__main__":
    model_name_or_path = '/models/Qwen-7B-Chat'
    output_path = '../merge_out'
    lora_path = '/Qwen-7B/output_qwen/checkpoint-500'
    apply_lora(model_name_or_path, output_path, lora_path)
```

报错信息如下：
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'QWenTokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. If you see this, DO NOT PANIC! This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/llm_projects/Qwen-7B/finetune/merge_lora.py", line 33, in <module>
    apply_lora(model_name_or_path, output_path, lora_path)
  File "/llm_projects/Qwen-7B/finetune/merge_lora.py", line 11, in apply_lora
    base_tokenizer = LlamaTokenizer.from_pretrained(model_name_or_path)
  File "/root/anaconda3/envs/qwen1/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/root/anaconda3/envs/qwen1/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/anaconda3/envs/qwen1/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "/root/anaconda3/envs/qwen1/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 166, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/root/anaconda3/envs/qwen1/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/root/anaconda3/envs/qwen1/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

进程已结束,退出代码1
```

### 运行环境 | Environment

```Markdown
- Transformers: 4.33.1
```

**Comment by jklj077** [comment]
请参考<https://github.com/QwenLM/Qwen#finetuning>部分说明试一下。
目前已知merge后保存不会存储QWenTokenzier和其它代码，请暂时参考<https://github.com/QwenLM/Qwen/issues/486>处理，把文件复制过去就好（或者`AutoTokenizer`加载再保存，不能用`LlamaTokenizer`的）。
