### ISSUE TITLE
单卡qlora微调报错

### ISSUE THREAD

**Issue by oklongmm** [QwenLM/Qwen#517]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

(ft_venv) [root@cs-1099-xkcs Qwen-main]# sh finetune/finetune_qlora_single_gpu.sh
[2023-10-24 09:53:49,376] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama,use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
CUDA extension not installed.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  4.17it/s]
Loading data...
Formatting inputs...Skip in lazy mode
Using /root/.cache/torch_extensions/py38_cu116 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu116/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda/bin/nvcc  -ccbin /root/anaconda3/envs/ft_venv/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/anaconda3/envs/ft_venv/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DBF16_AVAILABLE -std=c++14 -c /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o
FAILED: multi_tensor_adam.cuda.o
/usr/local/cuda/bin/nvcc  -ccbin /root/anaconda3/envs/ft_venv/bin/x86_64-conda-linux-gnu-cc -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/anaconda3/envs/ft_venv/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DBF16_AVAILABLE -std=c++14 -c /root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o
cc1plus: warning: unrecognized gcc debugging option: u
cc1plus: warning: unrecognized gcc debugging option: m
cc1plus: warning: unrecognized gcc debugging option: b
cc1plus: warning: unrecognized gcc debugging option: s
cc1plus: warning: unrecognized gcc debugging option: e
cc1plus: warning: unrecognized gcc debugging option: -
cc1plus: warning: unrecognized gcc debugging option: e
cc1plus: warning: unrecognized gcc debugging option: t
cc1plus: error: too many filenames given.  Type cc1plus --help for usage
nvcc fatal   : Failed to preprocess host compiler properties.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "finetune.py", line 363, in <module>
    train()
  File "finetune.py", line 356, in train
    trainer.train()
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1280, in prepare
    result = self._prepare_deepspeed(*args)
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1662, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1186, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1263, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 446, in load
    return self.jit_load(verbose)
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/deepspeed/ops/op_builder/builder.py", line 489, in jit_load
    op_module = load(name=self.name,
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/anaconda3/envs/ft_venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'

### 期望行为 | Expected Behavior

报错原因

### 复现方法 | Steps To Reproduce

 sh finetune/finetune_qlora_single_gpu.sh

### 运行环境 | Environment

```Markdown
python3.10
cuda11.6 
gcc9
```

### 备注 | Anything else?

无

**Comment by JustinLin610** [comment]
这应该deepspeed带来的问题，你可以确定下你是不是能正常使用deepspeed吧 这个fused adam是它那边的

**Comment by skyantao** [comment]
Emitting ninja build file /mnt/e/weight/torch_extensions/py39_cu117/fused_adam/build.ninja...
Building extension module fused_adam...

我的界面，你安装一下ninjia

**Comment by oklongmm** [comment]
通过把torch降低到1.13解决了
