### ISSUE TITLE
Qlora 双卡微调device map

### ISSUE THREAD

**Issue by yxk9810** [QwenLM/Qwen#529]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用单机双卡，跑的qlora_ds.sh, 报错如下: 

File "/kaggle/working/Qwen/finetune.py", line 367, in <module>
    train()
  File "/kaggle/working/Qwen/finetune.py", line 300, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2356, in from_pretrained
Traceback (most recent call last):
  File "/kaggle/working/Qwen/finetune.py", line 367, in <module>
    train()
  File "/kaggle/working/Qwen/finetune.py", line 300, in train
    raise ValueError("Passing along a `device_map` requires `low_cpu_mem_usage=True`")
ValueError: Passing along a `device_map` requires `low_cpu_mem_usage=True`
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2356, in from_pretrained
    raise ValueError("Passing along a `device_map` requires `low_cpu_mem_usage=True`")
ValueError: Passing along a `device_map` requires `low_cpu_mem_usage=True`
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

### 期望行为 | Expected Behavior

无

### 运行环境 | Environment

```Markdown
as requirements.txt
```

### 备注 | Anything else?

无

**Comment by jklj077** [comment]
参考 https://github.com/QwenLM/Qwen/issues/526#issuecomment-1778474398 
用最新代码试试呢~

**Comment by yxk9810** [comment]
还是一样的问题
