### ISSUE TITLE
[BUG] Lora多卡训练bug

### ISSUE THREAD

**Issue by WangXinghuo** [QwenLM/Qwen#558]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior
```
[1/2] /usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/deepspeed/ops/csrc/includes -I/home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/deepspeed/ops/csrc/adam -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include/TH -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include/THC -isystem /home/wangzhuoran/anaconda3/envs/qwen/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -std=c++17 -c /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/usr/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/deepspeed/ops/csrc/includes -I/home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/deepspeed/ops/csrc/adam -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include/torch/csrc/api/include -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include/TH -isystem /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/include/THC -isystem /home/wangzhuoran/anaconda3/envs/qwen/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -std=c++17 -c /home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc fatal   : Value 'c++17' is not defined for option 'std'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/wangzhuoran/anaconda3/envs/qwen/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

**Comment by jklj077** [comment]
根据提供的log，问题是deepspeed在编译fused_adam时报错。

原因可能是nvcc编译器版本跟conda环境中的cuda版本不匹配。

请提供下运行环境（比如`nvcc --version`的输出，以及PyTorch的具体版本号），以便辅助您解决问题。

**Comment by WangXinghuo** [comment]
nvcc --version结果如下：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

PyTorch版本：2.1.0+cu121

**Comment by WangXinghuo** [comment]
@jklj077 您好

nvcc --version结果如下：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

PyTorch版本：2.1.0+cu121

**Comment by jklj077** [comment]
目前看问题是版本不匹配，建议为系统安装一个版本为12.1的cuda (PyTorch的cu121表示用的12.1)，并设置为默认的cuda编译器。

**Comment by WangXinghuo** [comment]
@jklj077 请问这个是只在deepspeed上出现的错误吗，我使用单卡进行训练时可以正常运行

**Comment by jklj077** [comment]
嗯，对的，这个fused_adam是deepspeed默认的GPU优化器。
