### ISSUE TITLE
[BUG] <title>-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKS 训练时候报错

### ISSUE THREAD

**Issue by 937739823** [QwenLM/Qwen#582]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:01<00:00, 10.11it/s]
CUDA extension not installed.
CUDA extension not installed.
exllama_kernels not installed.
Traceback (most recent call last):
  File "/home/hanyong/Qwen/finetune.py", line 367, in <module>
    train()
  File "/home/hanyong/Qwen/finetune.py", line 342, in train
    model = get_peft_model(model, lora_config)
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 947, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 119, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 231, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 193, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 255, in _create_new_module
    AutoGPTQQuantLinear = get_auto_gptq_quant_linear(gptq_quantization_config)
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/other.py", line 416, in get_auto_gptq_quant_linear
    from auto_gptq.utils.import_utils import dynamically_import_QuantLinear
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/__init__.py", line 4, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/utils/peft_utils.py", line 20, in <module>
    from ..nn_modules.qlinear.qlinear_exllama import QuantLinear as QuantLinearExllama
  File "/usr/local/lib/python3.10/dist-packages/auto_gptq/nn_modules/qlinear/qlinear_exllama.py", line 14, in <module>
    from exllama_kernels import make_q4, q4_matmul
ImportError: /usr/local/lib/python3.10/dist-packages/exllama_kernels.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKSs

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python:3.10.12
- Transformers:4.35.0
- PyTorch:2.1.0a0+32f93b1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.2
```

### 备注 | Anything else?

Qwen-7B-chat推理时候没问题，但是训练时候 就会出现上述错误；还有int量化版本的推理时候也会出现上述错误~

**Comment by liangjiaxi24** [comment]
我也是遇到一样的问题。

**Comment by xusenlinzy** [comment]
可以试试  pip uninstall transformer-engine -y

**Comment by jklj077** [comment]
如楼上，AutoGPTQ对PyTorch和CUDA版本都有依赖哈(而且0.4.2好像还不支持PyTorch 2.1，可能得自己编译下AutoGPTQ)。

**Comment by jklj077** [comment]
https://github.com/PanQiWei/AutoGPTQ/issues/400
https://github.com/PanQiWei/AutoGPTQ/issues/414

**Comment by 2019zhou** [comment]
I check my pytorch version, my CUDA version. And then install the suitable autoGPTQ version. For me, install the 0.5.1 solve the problem.
