### ISSUE TITLE
qwen 使用 openai-api启动的问题

### ISSUE THREAD

**Issue by ccccccllllll** [QwenLM/Qwen#596]
我启动openai-api.py ， 其他的chat-next服务正常接入，但是使用dify的openai是无法接入的（换成chatglm3-6b正常），提示以下信息：

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/virtenv/qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 233, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home/virtenv/qwen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/virtenv/qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 236, in wrap
    await func()
  File "/home/virtenv/qwen/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in stream_response
    async for data in self.body_iterator:
  File "/home/openai/Qwen/openai_api.py", line 435, in predict
    raise HTTPException(
fastapi.exceptions.HTTPException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/virtenv/qwen/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/virtenv/qwen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/virtenv/qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 83, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.

**Comment by jklj077** [comment]
您好，streaming模式下，本repo中的openai_api.py尚不支持自定义stop_words（模型自身的stop_words无需设置）。dify可能在调用API时传入了有关参数，建议您排查下是否使用设置的特殊格式使用了不必要的stop或stop_sequences参数。

**Comment by ccccccllllll** [comment]
> 您好，streaming模式下，本repo中的openai_api.py尚不支持自定义stop_words（模型自身的stop_words无需设置）。dify可能在调用API时传入了有关参数，建议您排查下是否使用设置的特殊格式使用了不必要的stop或stop_sequences参数。

感谢您的解答，我尝试注释以下代码，目前问题已经解决
435     # if stop_words:
436           # TODO: It's a little bit tricky to trim stop words in the stream mode.
437    #     raise HTTPException(
438    #         status_code=400,
439    #         detail="Invalid request: custom stop words are not yet supported for stream mode.",
440    #     )

**Comment by jklj077** [comment]
这个主要担心有其它影响哈，比如dify里的模板用了特殊的结束符号，目前这个openai_api.py是支持不了的，请您判断哈~
