### ISSUE TITLE
使用多卡加载gptq int8量化的14B模型推理时报错AttributeError: can't set attribute

### ISSUE THREAD

**Issue by LimpidEarth** [QwenLM/Qwen#601]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

加载gptq int8量化后的14B模型进行推理，单卡可以正常加载推理。多卡加载推理时报如下错误：
```
Traceback (most recent call last):
  File "model.py", line 139, in <module>
    user_handler = UserHandler(os.getcwd())
  File "model.py", line 50, in __init__
    self.chat_model = ChatModel(args_dict)
  File "/ossfs/workspace/llmtuner/chat/stream_chat.py", line 23, in __init__
    self.model = dispatch_model(self.model)
  File "/ossfs/workspace/llmtuner/extras/misc.py", line 160, in dispatch_model
    return dispatch_model(model, device_map)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/big_modeling.py", line 390, in dispatch_model
    model.hf_device_map = device_map
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1674, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute
```

### 期望行为 | Expected Behavior

正常启动进行推理，返回推理结果

### 复现方法 | Steps To Reproduce

使用了如下方法加载模型，入参中传入了具体的model_name_or_path：

```python
def load_quantized_model_tokenizer(
        model_name_or_path: str,
        tokenizer_name_or_path: Optional[str] = None,
        max_memory: Optional[dict] = None,
        model_basename: Optional[str] = None,
        quantize_config: Optional[str] = None,
        trust_remote_code: bool = True,
        use_triton: bool = False,
        use_safetensors: bool = True,
        use_fast_tokenizer: bool = True,
        inject_fused_attention: bool = True,
        inject_fused_mlp: bool = True,
        disable_exllama: bool = True,  # default false
        use_flash_attn: bool = False,
        **kargs
):
    tokenizer = AutoTokenizer.from_pretrained(
        pretrained_model_name_or_path=tokenizer_name_or_path or model_name_or_path,
        use_fast=use_fast_tokenizer,
        trust_remote_code=trust_remote_code
    )
    if not tokenizer.pad_token_id:
        tokenizer.pad_token_id = tokenizer.eos_token_id


    logger.info('start loading gptq quantized model')
    model = AutoGPTQForCausalLM.from_quantized(
        model_name_or_path,
        max_memory=max_memory,
        low_cpu_mem_usage=True,
        use_triton=use_triton,
        inject_fused_attention=inject_fused_attention,
        inject_fused_mlp=inject_fused_mlp,
        use_cuda_fp16=True,
        quantize_config=quantize_config,
        model_basename=model_basename,
        use_safetensors=use_safetensors,
        trust_remote_code=trust_remote_code,
        warmup_triton=False,
        disable_exllama=disable_exllama,
        use_flash_attn=use_flash_attn,
        device_map='auto'  # added for debug
    )

    return model, tokenizer
```

然后使用如下方式进行模型dispatch：
```python
if model_args.quantized_model:
            self.model, self.tokenizer = load_quantized_model_tokenizer(model_name_or_path=model_args.model_name_or_path)
        else:
            self.model, self.tokenizer = load_model_and_tokenizer(model_args, finetuning_args)

        self.tokenizer.padding_side = "left"
        self.model = dispatch_model(self.model)
```
```python
def dispatch_model(model: "PreTrainedModel") -> "PreTrainedModel":
    r"""
    Dispatches a pre-trained model to GPUs with balanced memory.
    Borrowed from: https://github.com/huggingface/transformers/blob/v4.31.0/src/transformers/modeling_utils.py#L2803
    """
    if getattr(model, "is_loaded_in_8bit", False) or getattr(model, "is_loaded_in_4bit", False): # do nothing
        return model

    if torch.cuda.device_count() > 1:
        from accelerate import dispatch_model
        from accelerate.utils import infer_auto_device_map, get_balanced_memory

        if model._no_split_modules is None:
            raise ValueError("The model class needs to implement the `_no_split_modules` attribute.")

        kwargs = {"dtype": model.dtype, "no_split_module_classes": model._no_split_modules}
        max_memory = get_balanced_memory(model, **kwargs)
        # Make sure tied weights are tied before creating the device map.
        model.tie_weights()
        device_map = infer_auto_device_map(model, max_memory=max_memory, **kwargs)
        return dispatch_model(model, device_map)
    else:
        return model.cuda()
```
```python
def dispatch_model(
    model: nn.Module,
    device_map: Dict[str, Union[str, int, torch.device]],
    main_device: Optional[torch.device] = None,
    state_dict: Optional[Dict[str, torch.Tensor]] = None,
    offload_dir: Optional[Union[str, os.PathLike]] = None,
    offload_index: Optional[Dict[str, str]] = None,
    offload_buffers: bool = False,
    skip_keys: Optional[Union[str, List[str]]] = None,
    preload_module_classes: Optional[List[str]] = None,
):
    """
    Dispatches a model according to a given device map. Layers of the model might be spread across GPUs, offloaded on
    the CPU or even the disk.

    Args:
        model (`torch.nn.Module`):
            The model to dispatch.
        device_map (`Dict[str, Union[str, int, torch.device]]`):
            A dictionary mapping module names in the models `state_dict` to the device they should go to. Note that
            `"disk"` is accepted even if it's not a proper value for `torch.device`.
        main_device (`str`, `int` or `torch.device`, *optional*):
            The main execution device. Will default to the first device in the `device_map` different from `"cpu"` or
            `"disk"`.
        state_dict (`Dict[str, torch.Tensor]`, *optional*):
            The state dict of the part of the model that will be kept on CPU.
        offload_dir (`str` or `os.PathLike`):
            The folder in which to offload the model weights (or where the model weights are already offloaded).
        offload_index (`Dict`, *optional*):
            A dictionary from weight name to their information (`dtype`/ `shape` or safetensors filename). Will default
            to the index saved in `save_folder`.
        offload_buffers (`bool`, *optional*, defaults to `False`):
            Whether or not to offload the buffers with the model parameters.
        skip_keys (`str` or `List[str]`, *optional*):
            A list of keys to ignore when moving inputs or outputs between devices.
        preload_module_classes (`List[str]`, *optional*):
            A list of classes whose instances should load all their weights (even in the submodules) at the beginning
            of the forward. This should only be used for classes that have submodules which are registered but not
            called directly during the forward, for instance if a `dense` linear layer is registered, but at forward,
            `dense.weight` and `dense.bias` are used in some operations instead of calling `dense` directly.
    """
    # Error early if the device map is incomplete.
    check_device_map(model, device_map)

    # for backward compatibility
    is_quantized = getattr(model, "is_quantized", False) or getattr(model, "is_loaded_in_8bit", False)

    # We attach hooks if the device_map have at least 2 different devices. Otherwise, the model in already loaded
    # in the unique device and the user can decide where to dispatch the model.
    # If the model is quantized, we always force-dispatch the model
    if (len(set(device_map.values())) > 1) or is_quantized:
        if main_device is None:
            if set(device_map.values()) == {"cpu"} or set(device_map.values()) == {"cpu", "disk"}:
                main_device = "cpu"
            else:
                main_device = [d for d in device_map.values() if d not in ["cpu", "disk"]][0]

        if main_device != "cpu":
            cpu_modules = [name for name, device in device_map.items() if device == "cpu"]
            if state_dict is None and len(cpu_modules) > 0:
                state_dict = extract_submodules_state_dict(model.state_dict(), cpu_modules)

        disk_modules = [name for name, device in device_map.items() if device == "disk"]
        if offload_dir is None and offload_index is None and len(disk_modules) > 0:
            raise ValueError(
                "We need an `offload_dir` to dispatch this model according to this `device_map`, the following submodules "
                f"need to be offloaded: {', '.join(disk_modules)}."
            )
        if (
            len(disk_modules) > 0
            and offload_index is None
            and (not os.path.isdir(offload_dir) or not os.path.isfile(os.path.join(offload_dir, "index.json")))
        ):
            disk_state_dict = extract_submodules_state_dict(model.state_dict(), disk_modules)
            offload_state_dict(offload_dir, disk_state_dict)

        execution_device = {
            name: main_device if device in ["cpu", "disk"] else device for name, device in device_map.items()
        }
        execution_device[""] = main_device
        offloaded_devices = ["disk"] if main_device == "cpu" or main_device == "mps" else ["cpu", "disk"]
        offload = {name: device in offloaded_devices for name, device in device_map.items()}
        save_folder = offload_dir if len(disk_modules) > 0 else None
        if state_dict is not None or save_folder is not None or offload_index is not None:
            device = main_device if offload_index is not None else None
            weights_map = OffloadedWeightsLoader(
                state_dict=state_dict, save_folder=save_folder, index=offload_index, device=device
            )
        else:
            weights_map = None

        tied_params = find_tied_parameters(model)
        attach_align_device_hook_on_blocks(
            model,
            execution_device=execution_device,
            offload=offload,
            offload_buffers=offload_buffers,
            weights_map=weights_map,
            skip_keys=skip_keys,
            preload_module_classes=preload_module_classes,
        )
        # Attaching the hook may break tied weights, so we retie them
        retie_parameters(model, tied_params)
    else:
        device = list(device_map.values())[0]
        if device != "disk":
            model.to(device)
        else:
            raise ValueError(
                "You are trying to offload the whole model to the disk. Please use the `disk_offload` function instead."
            )
    model.hf_device_map = device_map
    return model
```

运行执行的命令是：
```
$CUDA_VISIBLE_DEVICES=0,1 python model.py
```

### 运行环境 | Environment

```Markdown
- OS: Linux
- Python: 3.8.16
- Transformers: 4.31.0 和 4.32.0都试过
- PyTorch: 2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.7
- accelerate: 0.21.0
```

**Comment by jklj077** [comment]
Hi, LimpidEarth

建议按照README中的方式来加载我们提供的模型。如果您采用了未预期的使用方式，需要您先自己debug的。

观察您提供的代码，我们发现您使用了AutoGPTQ里的`AutoGPTQForCausalLM.from_quantized`来加载模型，而不是我们样例代码中使用的transformers原生的`AutoModelForCausalLM.from_pretrained`配合`quantization_config`来加载模型。
AutoGPTQ中`from_quantized`返回的的模型类型是其自己定义的类型；跟transformers的模型类型是不一样的，很多操作是不兼容的。`model.model`才是transformers的`PreTrainedModel`类型。

就比如你这个报错，`from_quantized`返回的`model`的`hf_device_map`是个property，没有setter，没法直接赋值的，要dispatch的是`model.model`不是`model`。

https://github.com/PanQiWei/AutoGPTQ/blob/c70d29f05586d0221626e167c4e75265efc24967/auto_gptq/modeling/_base.py#L157-L159

如果您后续遇到了其它问题，且报错来源可能是我们提供的代码，我们会尽可能地帮助您排查有关问题。感谢理解！

**Comment by LimpidEarth** [comment]
> Hi, LimpidEarth
> 
> 建议按照README中的方式来加载我们提供的模型。如果您采用了未预期的使用方式，需要您先自己debug的。
> 
> 观察您提供的代码，我们发现您使用了AutoGPTQ里的`AutoGPTQForCausalLM.from_quantized`来加载模型，而不是我们样例代码中使用的transformers原生的`AutoModelForCausalLM.from_pretrained`配合`quantization_config`来加载模型。 AutoGPTQ中`from_quantized`返回的的模型类型是其自己定义的类型；跟transformers的模型类型是不一样的，很多操作是不兼容的。`model.model`才是transformers的`PreTrainedModel`类型。
> 
> 就比如你这个报错，`from_quantized`返回的`model`的`hf_device_map`是个property，没有setter，没法直接赋值的，要dispatch的是`model.model`不是`model`。
> 
> https://github.com/PanQiWei/AutoGPTQ/blob/c70d29f05586d0221626e167c4e75265efc24967/auto_gptq/modeling/_base.py#L157-L159
> 
> 如果您后续遇到了其它问题，且报错来源可能是我们提供的代码，我们会尽可能地帮助您排查有关问题。感谢理解！

我尝试按照这种方式加载模型：
![image](https://github.com/QwenLM/Qwen/assets/148319340/cad6c867-d78e-4742-ad34-1e5297ed7224)

发现会有如下的报错：
```
11/09/2023 14:31:54 - INFO - llmtuner.tuner.core.loader - start loading gptq quantized model
CUDA extension not installed.
CUDA extension not installed.
exllama_kernels not installed.
Traceback (most recent call last):
  File "model.py", line 139, in <module>
    user_handler = UserHandler(os.getcwd())
  File "model.py", line 50, in __init__
    self.chat_model = ChatModel(args_dict)
  File "/ossfs/workspace/llmtuner/chat/stream_chat.py", line 18, in __init__
    self.model, self.tokenizer = load_quantized_model_tokenizer(model_name_or_path=model_args.model_name_or_path)
  File "/ossfs/workspace/llmtuner/tuner/core/loader.py", line 256, in load_quantized_model_tokenizer
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, 
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2713, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/opt/conda/lib/python3.8/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/opt/conda/lib/python3.8/site-packages/optimum/gptq/quantizer.py", line 45, in <module>
    from auto_gptq import exllama_set_max_input_length
  File "/opt/conda/lib/python3.8/site-packages/auto_gptq/__init__.py", line 4, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "/opt/conda/lib/python3.8/site-packages/auto_gptq/utils/peft_utils.py", line 20, in <module>
    from ..nn_modules.qlinear.qlinear_exllama import QuantLinear as QuantLinearExllama
  File "/opt/conda/lib/python3.8/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllama.py", line 14, in <module>
    from exllama_kernels import make_q4, q4_matmul
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

transformers版本：4.34.0
auto-gptq版本：0.5.0

**Comment by jklj077** [comment]
大概率是transformers/exllama/pytorch/cuda间的版本依赖问题。
auto-gptq 0.5.0版本更新了exllama的实现，需要transformers 4.35.0版本支持，相关参数从disable_exllama变成了use_exllama和exllama_config两个参数。
建议尝试下退一个autogptq版本，比如到0.4.2（请选用合适的安装包）。

**Comment by Halloword** [comment]
@jklj077 hi,按照你的建议，我回退auto版本到0.4.2，确实没有报ImportError: libcudart.so.12: cannot open shared object file: No such file or directory这个error，但是报了需要升级auto到0.5.0的error
<img width="856" alt="Snipaste_2023-11-09_15-25-01" src="https://github.com/QwenLM/Qwen/assets/18690716/0e38e6cc-255d-44ea-870f-72d39b69058e">
我运行的代码是：
<img width="450" alt="Snipaste_2023-11-09_15-27-09" src="https://github.com/QwenLM/Qwen/assets/18690716/6dfc4918-aad1-4e36-ab25-fd921f98a725">
请问应该怎么解决？

**Comment by jklj077** [comment]
可能版本依赖坏掉了（最近好多版本更新，我们看下怎么说明下）：
- transformers=4.35.0 (optimum=1.14.0) autogptq>=0.5.0 pytorch=2.1 且 cuda 版本要匹配，参数是use_exllama=False
- transforemrs<4.35.0 (optimum<1.14.0) autogptq<0.5.0 pytorch<2.1 且 cuda 版本要匹配，参数是disable_exllama=True

**Comment by Halloword** [comment]
@jklj077 谢谢，按照transforemrs<4.35.0 (optimum<1.14.0) autogptq<0.5.0 pytorch<2.1这个配置，现在编译成功了

**Comment by LimpidEarth** [comment]
> @jklj077 谢谢，按照transforemrs<4.35.0 (optimum<1.14.0) autogptq<0.5.0 pytorch<2.1这个配置，现在编译成功了

我也按照这个配置改了一下，推理时报下面的错误：
```
Traceback (most recent call last):
  File "model.py", line 139, in <module>
    user_handler = UserHandler(os.getcwd())
  File "model.py", line 50, in __init__
    self.chat_model = ChatModel(args_dict)
  File "/ossfs/workspace/llmtuner/chat/stream_chat.py", line 18, in __init__
    self.model, self.tokenizer = load_quantized_model_tokenizer(model_name_or_path=model_args.model_name_or_path)
  File "/ossfs/workspace/llmtuner/tuner/core/loader.py", line 256, in load_quantized_model_tokenizer
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, 
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 560, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2864, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/admin/antlaw_v111_v1-int8-gptq/.
```
对应目录下的文件内容如下：
![image](https://github.com/QwenLM/Qwen/assets/148319340/6546c8a3-fb24-470a-9a21-9b030b12d44e)

**Comment by jklj077** [comment]
是您自己量化的模型吗？需要修改下config.json里的quantization_config部分的内容。

**Comment by jklj077** [comment]
quantize_config.json里应该是AutoGPTQ保存的相关信息，可以把这部分内容移动过去。

写法可以参考我们开源的量化模型(<https://huggingface.co/Qwen/Qwen-14B-Chat-Int8/blob/main/config.json>)，按你的quantize_config.json内容来填。

**Comment by LimpidEarth** [comment]
> https://huggingface.co/Qwen/Qwen-14B-Chat-Int8/blob/main/config.json

这个是quantize_config.json里面的内容
```
{
  "bits": 8,
  "group_size": 128,
  "damp_percent": 0.01,
  "desc_act": false,
  "static_groups": false,
  "sym": true,
  "true_sequential": true,
  "model_name_or_path": null,
  "model_file_base_name": null
}
```

我把它贴到了config.json的最后：
```
"model_type": "qwen",
  "no_bias": true,
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "onnx_safe": null,
  "rotary_emb_base": 10000,
  "rotary_pct": 1.0,
  "scale_attn_weights": true,
  "seq_length": 2048,
  "tie_word_embeddings": false,
  "tokenizer_class": "QWenTokenizer",
  "torch_dtype": "float16",
  "transformers_version": "4.32.0",
  "use_cache": true,
  "use_dynamic_ntk": true,
  "use_flash_attn": true,
  "use_logn_attn": true,
  "vocab_size": 159729,
  "quantization_config": {
      "bits": 8,
      "group_size": 128,
      "damp_percent": 0.01,
      "desc_act": false,
      "static_groups": false,
      "sym": true,
      "true_sequential": true,
      "model_name_or_path": null,
      "model_file_base_name": null
    }
}
```
运行还是报错'OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory XXXX'，是哪里还没配置对吗

**Comment by jklj077** [comment]
model_file_base_name用那个文件夹中的safetensors的名称填一下哈，保持两个一致

**Comment by LimpidEarth** [comment]
> model_file_base_name用那个文件夹中的safetensors的名称填一下哈，保持两个一致

修改成下面这样了，发现还是不行，一样的报错：
```
"model_type": "qwen",
  "no_bias": true,
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "onnx_safe": null,
  "rotary_emb_base": 10000,
  "rotary_pct": 1.0,
  "scale_attn_weights": true,
  "seq_length": 2048,
  "tie_word_embeddings": false,
  "tokenizer_class": "QWenTokenizer",
  "torch_dtype": "float16",
  "transformers_version": "4.32.0",
  "use_cache": true,
  "use_dynamic_ntk": true,
  "use_flash_attn": true,
  "use_logn_attn": true,
  "vocab_size": 159729,
  "quantization_config": {
      "bits": 8,
      "group_size": 128,
      "damp_percent": 0.01,
      "desc_act": false,
      "static_groups": false,
      "sym": true,
      "true_sequential": true,
      "model_name_or_path": null,
      "model_file_base_name": "gptq_model-8bit-128g"
   }
}
```

**Comment by jklj077** [comment]
@LimpidEarth 
AutoGPTQForCausalLM.from_quantized/from_pretrained不用改config.json，用model.model应当可以解决attribute error
AutoModelForCausalLM.from_pretrained要改config.json，由于transformers的内部机制，需要将safetensors文件的名字改成model，并尽量保持model_file_base_name一致。

我们理解后续两种方案您都实现了，模型均可加载。本issue先关闭了，如有其它涉及本repo代码的问题，请新开issue吧。感谢支持！
