### ISSUE TITLE
Q-LoRa微调Qwen-14B-Chat-Int4报错:ValueError: Target module QuantLinear() is not supported.或者TypeError: QWenPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'

### ISSUE THREAD

**Issue by zhouenxian** [QwenLM/Qwen#610]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在下面的环境下Q-lora微调Qwen-14-Chat-Int4报错：ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
环境:
auto-gptq                     0.5.0.dev0+cu117
optimum                       1.14.0
peft                          0.6.0
torch                         2.0.1+cu117
transformers                  4.34.0
..........
下面是报错完整信息:
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-11-10 09:06:25,437] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-10 09:06:25,479] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2023-11-10 09:06:28,151] [INFO] [comm.py:637:init_distributed] cdb=None
/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2023-11-10 09:06:28,198] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-10 09:06:28,198] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16, max_input_length) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16, max_input_length) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.37s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.47s/it]
Traceback (most recent call last):
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 369, in <module>
    train()
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 344, in train
    model = get_peft_model(model, lora_config)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 947, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 119, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 231, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 193, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 317, in _create_new_module
    raise ValueError(ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
Traceback (most recent call last):
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 369, in <module>
    train()
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 344, in train
    model = get_peft_model(model, lora_config)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 947, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 119, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 231, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 193, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 317, in _create_new_module
    raise ValueError(
ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 23549) of binary: /home/linewell/miniconda3/envs/nl2sql/bin/python
Traceback (most recent call last):
  File "/home/linewell/miniconda3/envs/nl2sql/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
```
------------------------------------------------------------
后来发现，以下有该error信息的相关讨论：
https://github.com/huggingface/peft/issues/1097
https://github.com/hiyouga/LLaMA-Factory/issues/1366
https://github.com/huggingface/transformers/issues/27380

升级 transformers==4.35.0 遇到新的报错：TypeError: QWenPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'
环境:
auto-gptq                     0.5.0.dev0+cu117
optimum                       1.14.0
peft                          0.6.0
torch                         2.0.1+cu117
transformers                  4.35.0
..........
完整报错信息:
```
Try importing flash-attention for faster inference...
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.16s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.17s/it]
Traceback (most recent call last):
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 369, in <module>
    train()
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 344, in train
    model = get_peft_model(model, lora_config)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 947, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 119, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 231, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 193, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 317, in _create_new_module
    raise ValueError(
ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
Traceback (most recent call last):
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 369, in <module>
    train()
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 344, in train
    model = get_peft_model(model, lora_config)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 947, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/peft_model.py", line 119, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 231, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 193, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 317, in _create_new_module
    raise ValueError(
ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12963) of binary: /home/linewell/miniconda3/envs/nl2sql/bin/python
Traceback (most recent call last):
  File "/home/linewell/miniconda3/envs/nl2sql/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================


```

### 期望行为 | Expected Behavior

https://github.com/huggingface/peft/issues/1097
https://github.com/hiyouga/LLaMA-Factory/issues/1366
https://github.com/huggingface/transformers/issues/27380
的讨论似乎是由于peft、tramsformers、auto-gptq 存在冲突，但是我分别尝试了auto-gptq ==0.5.0 auto-gptq ==0.6.0 peft=0.5.0 peft==0.6.0 transformers==4.34.0 transformers=4.35.0
仍无法解决

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10
- Transformers:4.34.0
- PyTorch:2.0.1+cu117
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):cuda 11.7
accelerate                    0.24.1
aiohttp                       3.8.6
aiosignal                     1.3.1
annotated-types               0.6.0
async-timeout                 4.0.3
attrs                         23.1.0
auto-gptq                     0.5.0.dev0+cu117
Brotli                        1.0.9
certifi                       2023.7.22
cffi                          1.15.1
charset-normalizer            2.0.4
coloredlogs                   15.0.1
cryptography                  41.0.3
datasets                      2.14.6
deepspeed                     0.12.2
dill                          0.3.7
einops                        0.7.0
filelock                      3.9.0
flash-attn                    2.3.3
frozenlist                    1.4.0
fsspec                        2023.10.0
gekko                         1.0.6
gmpy2                         2.1.2
hjson                         3.1.0
huggingface-hub               0.17.3
humanfriendly                 10.0
idna                          3.4
Jinja2                        3.1.2
MarkupSafe                    2.1.1
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
mpmath                        1.3.0
multidict                     6.0.4
multiprocess                  0.70.15
networkx                      3.1
ninja                         1.11.1.1
numpy                         1.24.3
optimum                       1.14.0
packaging                     23.2
pandas                        2.1.2
peft                          0.6.0
Pillow                        10.0.1
pip                           23.3
protobuf                      4.25.0
psutil                        5.9.6
py-cpuinfo                    9.0.0
pyarrow                       14.0.1
pycparser                     2.21
pydantic                      2.4.2
pydantic_core                 2.10.1
pynvml                        11.5.0
pyOpenSSL                     23.2.0
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3.post1
PyYAML                        6.0.1
regex                         2023.10.3
requests                      2.31.0
rouge                         1.0.1
safetensors                   0.4.0
scipy                         1.11.3
sentencepiece                 0.1.99
setuptools                    68.0.0
six                           1.16.0
sympy                         1.11.1
tiktoken                      0.5.1
tokenizers                    0.14.1
torch                         2.0.1
torchaudio                    2.0.2
torchvision                   0.15.2
tqdm                          4.66.1
transformers                  4.34.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.7.1
tzdata                        2023.3
urllib3                       1.26.18
wheel                         0.41.2
xxhash                        3.4.1
yarl                          1.9.2
```

**Comment by jklj077** [comment]
您好，请尝试降低autogpq到0.4.2看看（transformers维持4.34.x）。

**Comment by zhouenxian** [comment]
非常遗憾，当把autogpt版本降低到0.4.2，并且transformers==4.34.0  peft==0.5.0
![image](https://github.com/QwenLM/Qwen/assets/55723990/01727c1b-99fe-405e-9aa8-df6376058a32)
`出现：ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2+cu117, but only version above 0.4.99 are supported
`
error  information:
`WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-11-10 13:38:41,101] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-10 13:38:41,152] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-10 13:38:43,975] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-10 13:38:43,984] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-10 13:38:43,985] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
You passed `quantization_config` to `from_pretrained` but the model you're loading already has a `quantization_config` attribute and has already quantized weights. However, loading attributes (e.g. disable_exllama, use_cuda_fp16) will be overwritten with the one you passed to `from_pretrained`. The rest will be ignored.
Traceback (most recent call last):
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 369, in <module>
    train()
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 300, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2496, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 44, in <module>
    if is_auto_gptq_available():
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/optimum/utils/import_utils.py", line 116, in is_auto_gptq_available
    raise ImportError(
ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2+cu117, but only version above 0.4.99 are supported
Traceback (most recent call last):
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 369, in <module>
    train()
  File "/datas/work/zex/nl2sql/Qwen-main/finetune.py", line 300, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2496, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 44, in <module>
    if is_auto_gptq_available():
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/optimum/utils/import_utils.py", line 116, in is_auto_gptq_available
    raise ImportError(
ImportError: Found an incompatible version of auto-gptq. Found version 0.4.2+cu117, but only version above 0.4.99 are supported
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1027) of binary: /home/linewell/miniconda3/envs/nl2sql/bin/python
Traceback (most recent call last):
  File "/home/linewell/miniconda3/envs/nl2sql/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/linewell/miniconda3/envs/nl2sql/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
-----------------------------------`

**Comment by jklj077** [comment]
请参见后面链接中的版本说明调整下 https://github.com/QwenLM/Qwen/issues/601#issuecomment-1803328232

huggingface那一系列的包都得保证版本，您这里是optimum版本又高了。

**Comment by zhouenxian** [comment]
@jklj077  感谢
我按照transforemrs=4.34.0 ,optimum=1.13.0, autogptq==0.4.2+cu117  pytorch==2.0.1+cu117 这个配置，现在成功了
