### ISSUE TITLE
[BUG] 无法正常启动模型/对话

### ISSUE THREAD

**Issue by KJZH001** [QwenLM/Qwen#621]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
(Qwen) sakura@ubuntu:~/Qwen$ ./run.sh
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:12<00:00,  1.25it/s]
INFO:     Started server process [5650]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
./run.sh: line 1:  5650 Segmentation fault      (core dumped) python openai_api.py -c /home/sakura/Qwen-14B-Chat

```
这是第一次启动的记录，然后在模型收到第一条请求后，可以看到模型出现了异常崩溃

然后再次启动

```
(Qwen) sakura@ubuntu:~/Qwen$ ./run.sh 
Traceback (most recent call last):
  File "/home/sakura/Qwen/openai_api.py", line 16, in <module>
    from fastapi import FastAPI, HTTPException
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/_compat.py", line 20, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/exceptions.py", line 3, in <module>
    from pydantic import BaseModel, create_model
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/pydantic/__init__.py", line 3, in <module>
    import pydantic_core
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/pydantic_core/__init__.py", line 29, in <module>
    from .core_schema import CoreConfig, CoreSchema, CoreSchemaType, ErrorType
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
(Qwen) sakura@ubuntu:~/Qwen$ python cli_demo.py -c /home/sakura/Qwen-14B-Chat
Traceback (most recent call last):
  File "/home/sakura/Qwen/cli_demo.py", line 15, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/utils/__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/huggingface_hub/__init__.py", line 357, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 70, in <module>
    from ._inference_endpoints import InferenceEndpoint, InferenceEndpointType
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/huggingface_hub/_inference_endpoints.py", line 7, in <module>
    from .inference._client import InferenceClient
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/huggingface_hub/inference/_client.py", line 56, in <module>
    from huggingface_hub.inference._common import (
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/huggingface_hub/inference/_common.py", line 51, in <module>
    from ._text_generation import TextGenerationStreamResponse, _parse_text_generation_error
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py", line 36, in <module>
    from pydantic import validator
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/pydantic/__init__.py", line 3, in <module>
    import pydantic_core
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/pydantic_core/__init__.py", line 29, in <module>
    from .core_schema import CoreConfig, CoreSchema, CoreSchemaType, ErrorType
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
(Qwen) sakura@ubuntu:~/Qwen$ 

```

我们可以看到不论是cli demo 和 openai_api都出现了ValueError: bad marshal data (unknown type code)

请问如何解决呢？

### 期望行为 | Expected Behavior

我的第一条请求是在oneapi测试的，但是它崩溃了，我的预期应该是能够正常的响应于OneAPI并返回响应时间

### 复现方法 | Steps To Reproduce

见上方

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 23.04
- Python:3.10.10
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1


accelerate==0.24.1
annotated-types==0.6.0
anyio==3.7.1
certifi==2023.7.22
charset-normalizer==3.3.2
click==8.1.7
distro==1.8.0
einops==0.7.0
exceptiongroup==1.1.3
fastapi==0.104.1
filelock==3.13.1
flash-attn @ file:///home/sakura/Qwen/flash-attention
fsspec==2023.10.0
h11==0.14.0
httpcore==1.0.2
httpx==0.25.1
huggingface-hub==0.19.0
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.2.1
ninja==1.11.1.1
numpy==1.26.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.52
nvidia-nvtx-cu12==12.1.105
openai==1.2.3
packaging==23.2
psutil==5.9.6
pydantic==2.4.2
pydantic_core==2.10.1
PyYAML==6.0.1
regex==2023.10.3
requests==2.31.0
safetensors==0.4.0
scipy==1.11.3
sniffio==1.3.0
sse-starlette==1.6.5
starlette==0.27.0
sympy==1.12
tiktoken==0.5.1
tokenizers==0.13.3
torch==2.1.0
tqdm==4.66.1
transformers==4.32.0
transformers-stream-generator==0.0.4
triton==2.1.0
typing_extensions==4.8.0
urllib3==2.0.7
uvicorn==0.24.0.post1
```

### 备注 | Anything else?

(Qwen) sakura@ubuntu:~/Qwen$ cat run.sh
python openai_api.py -c /home/sakura/Qwen-14B-Chat

run.sh只有这么一行，写成脚本只是单纯的不想后续去记启动命令是什么，防止遗忘

**Comment by jklj077** [comment]
第一次遇到了Segmentation fault，很奇怪。有更多错误记录吗？
后续的报错是看着是Python complied bytecode给搞坏了，需要把相关的pyc文件删了（或者卸载再安装pydantic_core）。

**Comment by KJZH001** [comment]
> 第一次遇到了Segmentation fault，很奇怪。有更多错误记录吗？ 后续的报错是看着是Python complied bytecode给搞坏了，需要把相关的pyc文件删了（或者卸载再安装pydantic_core）。

对于14b模型没有更多的记录了

我今天尝试运行了7b模型，这是目前现有的log，使用的conda环境与14b模型相同

```
(Qwen) sakura@ubuntu:~/Qwen$ ./run-7b.sh
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.78it/s]
INFO:     Started server process [14649]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:44316 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sakura/Qwen/openai_api.py", line 395, in create_chat_completion
    response, _ = model.chat(
  File "/home/sakura/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1225, in chat
    outputs = self.generate(
  File "/home/sakura/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1347, in generate
    return super().generate(
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2760, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
目前它又出现了另外一个完全不同的错误，不过这次没有完全崩溃

另外我目前还没有重新安装pydantic_core，我会重装之后去再次尝试它

**Comment by ryanhe919** [comment]
哥们解决了吗，我也遇到了这个问题

**Comment by 13944087947** [comment]
me too 这个怎么解决啊

**Comment by EasonFang** [comment]
(Qwen) sakura@ubuntu:~/Qwen$ ./run-7b.sh
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  2.78it/s]
INFO:     Started server process [14649]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:44316 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/sakura/Qwen/openai_api.py", line 395, in create_chat_completion
    response, _ = model.chat(
  File "/home/sakura/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1225, in chat
    outputs = self.generate(
  File "/home/sakura/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 1347, in generate
    return super().generate(
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/datadisk/sakura/anaconda3/envs/Qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2760, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

有人解决这个报错了吗，web_demo启动正常，但是openai_py启动后通过oneapi聊天调用报错

**Comment by 2277419213** [comment]
[1094](https://github.com/QwenLM/Qwen/issues/1094)
我是这样解决的，你们可以试试

**Comment by KJZH001** [comment]
> [1094](https://github.com/QwenLM/Qwen/issues/1094) 我是这样解决的，你们可以试试

我后面使用了int4模型，虽然感觉不是量化和配置方面的问题，但是确实解决了，int4量化模型跑起来没有遇到问题

不过值得一提的是，openai风格的这个接口，确实非常不稳定，经常出现毛病

**Comment by 2277419213** [comment]
> > [1094](https://github.com/QwenLM/Qwen/issues/1094) 我是这样解决的，你们可以试试
> 
> 我后面使用了int4模型，虽然感觉不是量化和配置方面的问题，但是确实解决了，int4量化模型跑起来没有遇到问题
> 
> 不过值得一提的是，openai风格的这个接口，确实非常不稳定，经常出现毛病

但是我用int版本的他的推理很慢
