### ISSUE TITLE
[BUG] <title>python openai_api.py后报错'FieldInfo' object has no attribute 'required'

### ISSUE THREAD

**Issue by qihangf** [QwenLM/Qwen#630]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 复现方法 | Steps To Reproduce

python openai_api.py --server-name 0.0.0.0 --server-port 7905 -c /home/wyxx/warBackup/ner/qwen/model后遇到的问题

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 16.04
- Python:3.9
- Transformers:4.32.0
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.6
- GPU v100
```

### 备注 | Anything else?

具体报错
/data/software/anaconda3/lib/python3.9/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driverby downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your versionof the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/data/software/anaconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/data/software/anaconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
[2023-11-14 13:38:57,861] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda(auto detect)
/data/software/anaconda3/lib/python3.9/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/data/software/anaconda3/lib/python3.9/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1130, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/data/software/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 27, in <module>
    from ..deepspeed import is_deepspeed_zero3_enabled
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/deepspeed.py", line 37, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 133, in <module>
    from .launch import (
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/data/software/anaconda3/lib/python3.9/site-packages/accelerate/utils/other.py", line 30, in <module>
    from deepspeed import DeepSpeedEngine
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/__init__.py", line 16, in <module>
    from . import module_inject
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 792, in <module>
    from ..pipe import PipelineModule
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 6,in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/__init__.py", line 6,in <module>
    from .partition_parameters import ZeroParamType
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 616, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 618, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/data/software/anaconda3/lib/python3.9/site-packages/deepspeed/runtime/config_utils.py", line 115, in get_config_default
    assert not config.__fields__.get(
AttributeError: 'FieldInfo' object has no attribute 'required'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wyxx/warBackup/ner/qwen/openai_api.py", line 512, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 174, in check_imports
    importlib.import_module(imp)
  File "/data/software/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers_stream_generator/__init__.py", line 1, in <module>
    from .main import init_stream_support
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers_stream_generator/main.py", line1, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1121, in __getattr__
    value = getattr(module, name)
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1120, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/software/anaconda3/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1132, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
'FieldInfo' object has no attribute 'required'

**Comment by JianxinMa** [comment]
@jklj077 我看log里有deepspeed，这个是用户finetune过的ckpt吗？我不太了解deepspeed finetune这块。猜测与 pydantic 冲突相关。deepspeed要求v1，目前的open_api.py要求v2 —— 不过可以简单把open_api.py里一些地方改成兼容v1。

**Comment by JianxinMa** [comment]
@jklj077 https://github.com/QwenLM/Qwen/pull/632/files 帮忙double check并merge下这个PR（让 openai_api.py兼容pydantic v1）

然后，楼主可以尝试用 https://github.com/QwenLM/Qwen/pull/632/files 这个PR里的 openai_api.py，并安装与deepspeed兼容的pydantic 版本（可能是 `pip install "pydantic<2.0.0"`，不太确定)

**Comment by jklj077** [comment]
@qihangf 我们观察到您加载了DeepSpeed ZeRO-3微调后的checkpoint并可能使用bitsandbytes库。

1. DeepSpeed与本repo中openai_api.py对pydantic的版本要求有冲突，该问题已在主分支fix，请尝试回退pydantic版本小于2.0.0并使用更新后的openai_api.py
2. 目前本repo中量化相关均依赖AutoGPTQ，bitsandbytes目前我不确定是否可用。

**Comment by qihangf** [comment]
谢谢大佬们，果然是pydantic版本问题

**Comment by xxWeiDG** [comment]
请问一下，最后用什么版本的pydantic才好用啊

**Comment by qingyue2014** [comment]
> 请问一下，最后用什么版本的pydantic才好用啊

我最后改用了1.9.0版本没有问题了
