### ISSUE TITLE
[BUG] <title> pyo3_runtime.PanicException: no entry found for key

### ISSUE THREAD

**Issue by Xccanxin** [QwenLM/Qwen#633]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
Qwen7b模型 + lora微调，batch推理的时候tokenizer.decode_tokens报错如下，进一步debug发现是tokenizer.decode(token)无法识别token=151870 151856 151856

/output 下的文件：
qwen.tiktoken长度为151643
config.vocab_size为151936

thread '<unnamed>' panicked at 'no entry found for key', src/lib.rs:201:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/LLM/beginner/Qwen/eval/batch_inference.py", line 51, in <module>
    batch_response = [
  File "/home/xxx/PycharmProjects/LLM/beginner/Qwen/eval/batch_inference.py", line 52, in <listcomp>
    decode_tokens(
  File "/home/xxx/PycharmProjects/LLM/beginner/Qwen/eval/qwen_generation_utils.py", line 275, in decode_tokens
    return _decode_chatml(
  File "/home/xxx/PycharmProjects/LLM/beginner/Qwen/eval/qwen_generation_utils.py", line 244, in _decode_chatml
    trim_decode_tokens = tokenizer.decode(tokens[:eod_token_idx], errors=errors)[raw_text_len:]
  File "/home/xxx/anaconda3/envs/py39/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3550, in decode
    return self._decode(
  File "/home/xxx/.cache/huggingface/modules/transformers_modules/Qwen-7B/tokenization_qwen.py", line 246, in _decode
    return self.tokenizer.decode(token_ids, errors=errors or self.errors)
  File "/home/xxx/anaconda3/envs/py39/lib/python3.9/site-packages/tiktoken/core.py", line 254, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
pyo3_runtime.PanicException: no entry found for key
```

### 期望行为 | Expected Behavior

正常推理

### 复现方法 | Steps To Reproduce

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import GenerationConfig
from qwen_generation_utils import make_context, decode_tokens, get_stop_words_ids
from peft import get_peft_config, PeftModel, PeftConfig, get_peft_model, LoraConfig, TaskType

tokenizer = AutoTokenizer.from_pretrained(
    '/output',
    #'Qwen/Qwen-7B',
    pad_token='<|extra_0|>',
    eos_token='<|endoftext|>',
    padding_side='left',
    trust_remote_code=True
)
model = AutoModelForCausalLM.from_pretrained(
    'Qwen/Qwen-7B',
    pad_token_id=tokenizer.pad_token_id,
    device_map="auto",
    trust_remote_code=True
).eval()

peft_model_id = "/output"
config = PeftConfig.from_pretrained(peft_model_id)
model = PeftModel.from_pretrained(model, peft_model_id)

model.generation_config = GenerationConfig.from_pretrained('Qwen/Qwen-7B', pad_token_id=tokenizer.pad_token_id)

all_raw_text = ["类型#上衣*材质#牛仔布*颜色#白色*风格#简约*图案#刺绣*衣样式#外套*衣款式#破洞"]
batch_raw_text = []
for q in all_raw_text:
    raw_text, _ = make_context(
        tokenizer,
        q,
        system="You are a helpful assistant.",
        # max_window_size=model.generation_config.max_window_size,
        # chat_format=model.generation_config.chat_format,
    )
    batch_raw_text.append(raw_text)

batch_input_ids = tokenizer(batch_raw_text, padding='longest')
batch_input_ids = torch.LongTensor(batch_input_ids['input_ids']).to(model.device)
batch_out_ids = model.generate(
    inputs=batch_input_ids,
    # batch_input_ids, # generate() takes 1 positional argument but 2 were given
    # return_dict_in_generate=False,
    generation_config=model.generation_config
)
padding_lens = [batch_input_ids[i].eq(tokenizer.pad_token_id).sum().item() for i in range(batch_input_ids.size(0))]
print("batch_out_ids",batch_out_ids)
''' ERROR!'''
for i,token in enumerate(batch_out_ids[0]):
    try:
        tokenizer.decode(token)
    except:
        print(token) # 151870 151856 151856


batch_response = [
    decode_tokens(
        batch_out_ids[i][padding_lens[i]:],
        tokenizer,
        raw_text_len=len(batch_raw_text[i]),
        context_length=(batch_input_ids[i].size(0)-padding_lens[i]),
        # chat_format="chatml",
        chat_format="raw",
        verbose=False,
        errors='replace'
    ) for i in range(len(all_raw_text))
]
print(batch_response)
```

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
这种情况一般是模型输出该停下来的是时候没停下来。

方便的话，请提供下非异常部分的decode结果，以判断是否是该问题。
```
for i,token in enumerate(batch_out_ids[0]):
    try:
        print(tokenizer.decode(token))
    except:
        print(token) # 151870 151856 151856
```

如是该问题，建议检查微调过程是否正常，比如embedding/output layer是否有训练、数据量是否足够、是否有拟合数据等。

**Comment by Xccanxin** [comment]
> 这种情况一般是模型输出该停下来的是时候没停下来。
> 
> 方便的话，请提供下非异常部分的decode结果，以判断是否是该问题。
> 
> ```
> for i,token in enumerate(batch_out_ids[0]):
>     try:
>         print(tokenizer.decode(token))
>     except:
>         print(token) # 151870 151856 151856
> ```
> 
> 如是该问题，建议检查微调过程是否正常，比如embedding/output layer是否有训练、数据量是否足够、是否有拟合数据等。

微调设置及代码修改：
lora_target_modules=c_attn，参数量为0.05%，line341取消额外微调的["wte", "lm_head"]
额外设置model.generation_config.max_new_tokens = 256，与lora微调时model_max_length=256保持一致

输出前100个：
```
print(tokenizer.decode(batch_out_ids[0][:100]))
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
类型#上衣*材质#牛仔布*颜色#白色*风格#简约*图案#刺绣*衣样式#外套*衣款式#破洞<|im_end|>
<|im_start|>assistant
牛仔外套永远是女孩们衣柜里必不可少的时髦单品，简约的设计给人舒适随性感，同时也不失个性。帅气的破洞设计个性又时髦，点缀白色的刺绣logo，精致感十足。ยืน
```

输出100之后：
```
for i,token in enumerate(batch_out_ids[0][100:]):
    try:
        print(tokenizer.decode(token))
    except:
        print(token) # 151870 151856 151856
```

部分输出如下

```
ไม่เคย
ค้า
𬳵
 prostituerte
ﮁ
헠
เด่น
 כאיל
 الْ
tensor(151899, device='cuda:1')
ตัวเอง
꿱
ชีวิต
لَ
얊
𝄅
เกียร
 פוסטיםטים
```


前100token的输出符合预期，后面的token有无法识别的id。

**Comment by jklj077** [comment]
> 取消额外微调的["wte", "lm_head"]

因为您微调的是基模型，这两个一定要微调的，不能取消的。基模型没见过chat里的两个特殊token，不训练的话，模型生成不了格式的标识符，该停止的时候没停下来，就出异常了。

README中有**明确说明**的
> **注意，如果你使用预训练模型进行LoRA微调，而非chat模型，模型的embedding和输出层的参数将被设为可训练的参数。这是因为预训练模型没有学习过ChatML格式中的特殊token，因此需要将这部分参数设为可训练才能让模型学会理解和预测这些token。这也意味着，假如你的训练引入新的特殊token，你需要通过代码中的modules_to_save将这些参数设为可训练的参数。** 此外，这部分训练参数的引入会影响ZeRO 3的使用，因此我们默认推荐使用ZeRO 2。当然，如果你不需要引入这部分训练参数，你可以通过替换DeepSpeed的配置文件来使用ZeRO 3。如果你想节省显存占用，可以考虑使用chat模型进行LoRA微调，显存占用将大幅度降低。下文的显存占用和训练速度的记录将详细介绍这部分细节。

**Comment by jklj077** [comment]
> 如果不使用chatml格式，并修改代码的数据读取方式，lora微调+取消额外微调的["wte", "lm_head"]就不会出现这个问题？

不使用chatml格式的话，如果不微调["wte", "lm_head"]，您也需要选定一种格式来描述对话，例如`\n\nHuman: ...\n\nAssistant: ...`这种纯自然语言的模板，并按该格式进行相应的数据处理以及推理过程中的中止条件识别。

> 以及raw格式不使用<im_start><im_end>，那么在处理数据的时候是否有标准的start/end标志？

对话轮与轮间的标志根据您使用的格式来确定。整条数据的结束可以复用`<|endoftext|>`这一特殊符号。
