### ISSUE TITLE
[BUG] 8xA100 80G 开启flash-atten微调Qwen-7B-Chat和Qwen-14B-Chat，报错：FWD: Unsupported hidden_size or types: 4096BFloat16FloatFloatFloatFloat

### ISSUE THREAD

**Issue by baibaiw5** [QwenLM/Qwen#635]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

1.下载最新的huggingface 7B和14B模型
2.config.json中："use_flash_attn": "auto"
3.程序异常：
RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
Traceback (most recent call last):
  File "/data/FastChat.new/fastchat/train/train_qwen.py", line 302, in <module>
    train()
  File "/data/FastChat.new/fastchat/train/train_qwen.py", line 291, in train
    trainer.train(resume_from_checkpoint=True)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 2801, in compute_loss
    outputs = model(**inputs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 1131, in forward
    transformer_outputs = self.transformer(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 949, in forward
    outputs = torch.utils.checkpoint.checkpoint(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 945, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 681, in forward
    layernorm_output = self.ln_2(layernorm_input)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 1442, in forward
    return rms_norm(x, self.weight, self.eps)
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/flash_attn/ops/rms_norm.py", line 15, in rms_norm
    return DropoutAddLayerNormFn.apply(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/flash_attn/ops/layer_norm.py", line 334, in forward
    zmat, xmat, dmask, mu, rsigma = _dropout_add_layer_norm_forward(
  File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/flash_attn/ops/layer_norm.py", line 33, in _dropout_add_layer_norm_forward
    zmat, xmat, dmask, mu, rsigma = dropout_layer_norm.dropout_add_ln_fwd(
RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat

### 期望行为 | Expected Behavior

qwen模型开启flash-attn进行全量微调时，是否需要特殊设置。
目前关闭flash-attn时，模型是可以正常微调，但是速度比百川等同类模型慢。

### 复现方法 | Steps To Reproduce

1.使用以下参数微调模型
torchrun --nproc_per_node=8 --master_port=20001 fastchat/train/train_qwen.py \
    --model_name_or_path /data/models/Qwen/Qwen-7B-Chat  \
    --data_path data.json \
    --bf16 True \
    --output_dir /data1/checkpoints/qwen_rec_version1  \
    --num_train_epochs 6 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 400 \
    --save_total_limit 50 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'QWenBlock' \
    --tf32 True \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --report_to tensorboard \
    --lazy_preprocess True

### 运行环境 | Environment

```Markdown
- OS:ubuntu 22.24
- Python: 3.10
- Transformers: 4.34.0
- PyTorch: 2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
```

### 备注 | Anything else?

无

**Comment by jklj077** [comment]
训练脚本用的哪个呢

**Comment by jklj077** [comment]
这个问题大概率是某个地方类型转换不对（log里是RMSNorm那里），如果是使用repo中的finetune脚本的话，目前用flash-attn也是不会出现这类问题的。

**Comment by lebronjamesking** [comment]
> ### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?
> * [x]  我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions
> 
> ### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?
> * [x]  我已经搜索过FAQ | I have searched FAQ
> 
> ### 当前行为 | Current Behavior
> 1.下载最新的huggingface 7B和14B模型 2.config.json中："use_flash_attn": "auto" 3.程序异常： RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat Traceback (most recent call last): File "/data/FastChat.new/fastchat/train/train_qwen.py", line 302, in train() File "/data/FastChat.new/fastchat/train/train_qwen.py", line 291, in train trainer.train(resume_from_checkpoint=True) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1591, in train return inner_training_loop( File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop tr_loss_step = self.training_step(model, inputs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 2776, in training_step loss = self.compute_loss(model, inputs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/transformers/trainer.py", line 2801, in compute_loss outputs = model(**inputs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward return model_forward(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in **call** return convert_to_fp32(self.model_forward(*args, **kwargs)) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast return func(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward output = self._fsdp_wrapped_module(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 636, in forward return model_forward(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/accelerate/utils/operations.py", line 624, in **call** return convert_to_fp32(self.model_forward(*args, **kwargs)) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast return func(*args, **kwargs) File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 1131, in forward transformer_outputs = self.transformer( File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 949, in forward outputs = torch.utils.checkpoint.checkpoint( File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint return CheckpointFunction.apply(function, preserve, *args) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward outputs = run_function(*args) File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 945, in custom_forward return module(*inputs, use_cache, output_attentions) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 748, in forward output = self._fsdp_wrapped_module(*args, **kwargs) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 681, in forward layernorm_output = self.ln_2(layernorm_input) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/home/baimingbai/.cache/huggingface/modules/transformers_modules/Qwen-14B-Chat/modeling_qwen.py", line 1442, in forward return rms_norm(x, self.weight, self.eps) File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/flash_attn/ops/rms_norm.py", line 15, in rms_norm return DropoutAddLayerNormFn.apply( File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/flash_attn/ops/layer_norm.py", line 334, in forward zmat, xmat, dmask, mu, rsigma = _dropout_add_layer_norm_forward( File "/data/anaconda3/envs/qwen/lib/python3.10/site-packages/flash_attn/ops/layer_norm.py", line 33, in _dropout_add_layer_norm_forward zmat, xmat, dmask, mu, rsigma = dropout_layer_norm.dropout_add_ln_fwd( RuntimeError: FWD: Unsupported hidden_size or types: 5120BFloat16FloatFloatFloatFloat
> 
> ### 期望行为 | Expected Behavior
> qwen模型开启flash-attn进行全量微调时，是否需要特殊设置。 目前关闭flash-attn时，模型是可以正常微调，但是速度比百川等同类模型慢。
> 
> ### 复现方法 | Steps To Reproduce
> 1.使用以下参数微调模型 torchrun --nproc_per_node=8 --master_port=20001 fastchat/train/train_qwen.py --model_name_or_path /data/models/Qwen/Qwen-7B-Chat --data_path data.json --bf16 True --output_dir /data1/checkpoints/qwen_rec_version1 --num_train_epochs 6 --per_device_train_batch_size 2 --per_device_eval_batch_size 2 --gradient_accumulation_steps 16 --evaluation_strategy "no" --save_strategy "steps" --save_steps 400 --save_total_limit 50 --learning_rate 2e-5 --weight_decay 0. --warmup_ratio 0.03 --lr_scheduler_type "cosine" --logging_steps 1 --fsdp "full_shard auto_wrap" --fsdp_transformer_layer_cls_to_wrap 'QWenBlock' --tf32 True --model_max_length 4096 --gradient_checkpointing True --report_to tensorboard --lazy_preprocess True
> 
> ### 运行环境 | Environment
> ```
> - OS:ubuntu 22.24
> - Python: 3.10
> - Transformers: 4.34.0
> - PyTorch: 2.0.1
> - CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 11.8
> ```
> 
> ### 备注 | Anything else?
> 无

请问Qwen2现在也是fsdp_transformer_layer_cls_to_wrap=QwenBlock么
