### ISSUE TITLE
在本地运行int4 14b模型时，启用kv cache量化，遇到AttributeError: 'tuple' object has no attribute 'size'的报错，找不到问题。[BUG] <title>

### ISSUE THREAD

**Issue by yuunnn-w** [QwenLM/Qwen#659]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

执行cli_demo.py
其中载入模型部分修改为：
```python
model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
        use_cache_quantization=True,
        use_cache_kernel=True,
    ).eval()
```
增加了kv cache量化。
当执行推理时，遇到如下报错：
```
User> 你好
Traceback (most recent call last):
  File "D:\GPT\Qwen\cli_demo.py", line 212, in <module>
    main()
  File "D:\GPT\Qwen\cli_demo.py", line 200, in main
    for response in model.chat_stream(tokenizer, query, history=history, generation_config=config):
  File "C:\Users\jiaxi/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\6e723788f052cc2f9c64d55aef7af161da75e2be\modeling_qwen.py", line 1229, in stream_generator
    for token in self.generate_stream(
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\transformers_stream_generator\main.py", line 931, in sample_stream
    outputs = self(
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jiaxi/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\6e723788f052cc2f9c64d55aef7af161da75e2be\modeling_qwen.py", line 1058, in forward
    transformer_outputs = self.transformer(
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jiaxi/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\6e723788f052cc2f9c64d55aef7af161da75e2be\modeling_qwen.py", line 889, in forward
    outputs = block(
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jiaxi/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\6e723788f052cc2f9c64d55aef7af161da75e2be\modeling_qwen.py", line 609, in forward
    attn_outputs = self.attn(
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\jiaxi/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\6e723788f052cc2f9c64d55aef7af161da75e2be\modeling_qwen.py", line 505, in forward
    torch.ones((key.size(1), key.size(1)), dtype=torch.bool, device=key.device)
AttributeError: 'tuple' object has no attribute 'size'
```
接着程序就会直接退出。

### 期望行为 | Expected Behavior

我期望模型可以正常运行，可当增加
use_cache_quantization=True,
use_cache_kernel=True,
这两个量化参数时，执行推理出现报错。
当去掉这两个参数时，模型正常推理无误。

### 复现方法 | Steps To Reproduce

1.安装模型及依赖。
2.将cli_demo.py中DEFAULT_CKPT_PATH宏改为'Qwen/Qwen-14B-Chat-Int4'。
3.将cli_demo.py中def _load_model_tokenizer(args):函数中，加载模型的部分增加如下参数：
```
model = AutoModelForCausalLM.from_pretrained(
        args.checkpoint_path,
        device_map=device_map,
        trust_remote_code=True,
        resume_download=True,
        use_cache_quantization=True,
        use_cache_kernel=True,
    ).eval()
```
4.执行python cli_demo.py 并提问。

### 运行环境 | Environment

```Markdown
- OS: Windows 11
- Python: 3.10.13
- Transformers: 4.32.0
- PyTorch: 2.1.1+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

### 备注 | Anything else?

关键点有三个：
1. Windows 11环境
2. 采用Qwen-14B-Chat-Int4模型
3. 载入模型时开启use_cache_quantization=True,use_cache_kernel=True这两个参数。

## 初步推断是int4模型在win 11环境下对kv cache支持有问题。

**Comment by yuunnn-w** [comment]
如果关闭kv cache功能，使用openai_api.py脚本，使用ChatGPT Next的ui访问时会报告如下错误：
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\sse_starlette\sse.py", line 249, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\sse_starlette\sse.py", line 252, in wrap
    await func()
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\sse_starlette\sse.py", line 239, in stream_response
    async for data in self.body_iterator:
  File "D:\GPT\Qwen\openai_api.py", line 449, in predict
    for new_response in response_generator:
  File "C:\Users\jiaxi/.cache\huggingface\modules\transformers_modules\Qwen\Qwen-14B-Chat-Int4\6e723788f052cc2f9c64d55aef7af161da75e2be\modeling_qwen.py", line 1229, in stream_generator
    for token in self.generate_stream(
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\torch\utils\_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "C:\ProgramData\Anaconda3\envs\qwen\lib\site-packages\transformers_stream_generator\main.py", line 969, in sample_stream
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

这是精度溢出了？

如果用cli_demo.py可以正常推理

**Comment by jklj077** [comment]
> 如果关闭kv cache功能，使用openai_api.py脚本，使用ChatGPT Next的ui访问时会报告如下错误

您看下temperature传的多少，量化模型容易出这个问题，建议不要调temperature，调topp。

**Comment by yuunnn-w** [comment]
> > 如果关闭kv cache功能，使用openai_api.py脚本，使用ChatGPT Next的ui访问时会报告如下错误
> 
> 您看下temperature传的多少，量化模型容易出这个问题，建议不要调temperature，调topp。

理解您的意思，可能是温度太高了导致采样溢出，那上面那个kv cacahe问题是怎么回事呢？您有头绪吗？😭如果不用kv cache的话我的显存不够用啊呜呜呜

**Comment by jklj077** [comment]
kv cache错误已于最新模型代码中修复，感谢报告~
