### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by sunbeibei-hub** [QwenLM/Qwen#680]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

used：
```
pip install vllm
pip install "fschat[model_worker,webui]"
```
deploy Qwen，but error
```
python -m fastchat.serve.vllm_worker --model-path  /data/search/bei/Models/Qwen/Qwen-14B-Chat --trust-remote-code --gpu-memory-utilization 0.7
```

error is
```
INFO 11-28 12:38:33 llm_engine.py:72] Initializing an LLM engine with config: model='/data/search/bei/Models/Qwen/Qwen-14B-Chat', tokenizer='/data/search/bei/Models/Qwen/Qwen-14B-Chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
WARNING 11-28 12:38:34 tokenizer.py:66] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
2023-11-28 12:38:36 | ERROR | stderr | Traceback (most recent call last):
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-11-28 12:38:36 | ERROR | stderr |     return _run_code(code, main_globals, None,
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/runpy.py", line 87, in _run_code
2023-11-28 12:38:36 | ERROR | stderr |     exec(code, run_globals)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/fastchat/serve/vllm_worker.py", line 259, in <module>
2023-11-28 12:38:36 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
2023-11-28 12:38:36 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
2023-11-28 12:38:36 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 305, in _init_engine
2023-11-28 12:38:36 | ERROR | stderr |     return engine_class(*args, **kwargs)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
2023-11-28 12:38:36 | ERROR | stderr |     self._init_workers(distributed_init_method)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 142, in _init_workers
2023-11-28 12:38:36 | ERROR | stderr |     self._run_workers(
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
2023-11-28 12:38:36 | ERROR | stderr |     output = executor(*args, **kwargs)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/worker/worker.py", line 70, in init_model
2023-11-28 12:38:36 | ERROR | stderr |     self.model = get_model(self.model_config)
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/model_executor/model_loader.py", line 98, in get_model
2023-11-28 12:38:36 | ERROR | stderr |     model.load_weights(model_config.model, model_config.download_dir,
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/model_executor/models/qwen.py", line 272, in load_weights
2023-11-28 12:38:36 | ERROR | stderr |     for name, loaded_weight in hf_model_weights_iterator(
2023-11-28 12:38:36 | ERROR | stderr |   File "/home/search/miniconda3/envs/bei_Qwen/lib/python3.9/site-packages/vllm/model_executor/weight_utils.py", line 244, in hf_model_weights_iterator
2023-11-28 12:38:36 | ERROR | stderr |     with safe_open(st_file, framework="pt") as f:
2023-11-28 12:38:36 | ERROR | stderr | safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

### 运行环境 | Environment

```Markdown
- OS:centos7
- Python:3.9.18
- Transformers:4.35.2
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
参见 https://github.com/QwenLM/Qwen/issues/462

一般情况下是模型下载过程中可能网络不稳定，导致模型文件损坏了，重试一般能够解决该问题。README中提供了从ModelScope通过snapshot download手动下载的方式，也可以尝试看看。
