### ISSUE TITLE
[BUG] <title> 7B int4 qlora 微调出现QWenTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by yxk9810** [QwenLM/Qwen#682]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

2023-11-28 08:00:28,648] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loading checkpoint shards: 100%|██████████████████| 8/8 [01:04<00:00,  8.11s/it]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 298, in quantize_model
    tokenizer = AutoTokenizer.from_pretrained(tokenizer)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 724, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kaggle/working/Qwen/finetune.py", line 366, in <module>
    train()
  File "/kaggle/working/Qwen/finetune.py", line 300, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3157, in from_pretrained
    quantizer.quantize_model(model, quantization_config.tokenizer)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 300, in quantize_model
    raise ValueError(
ValueError: We were not able to get the tokenizer using `AutoTokenizer.from_pretrained`
                    with the string that you have passed Qwen/Qwen-7B-Chat. If you have a custom tokenizer, you can pass it as input.
                    For now, we only support quantization for text model. Support for vision, speech and multimodel will come later.

### 期望行为 | Expected Behavior

no

### 复现方法 | Steps To Reproduce

参考kaggle链接：https://www.kaggle.com/code/jackiewu/qwen-int4-finetune

### 运行环境 | Environment

```Markdown
- OS:
- Python:3.10.12
- Transformers:4.32.0
- PyTorch:2.0.1
- auto-gptq:0.4.2 ,optimum:0.13.2 
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

no

**Comment by jklj077** [comment]
您好，我们无法打开您提供的kaggle链接。

根据报错，请检查模型目录下是否有tokenization_qwen.py、tokenization_config.jsony和qwen.tiktoken这个三个文件。如果您使用了自定义代码，请确保trust_remote_code设置为True。

**Comment by yxk9810** [comment]
代码链接可参考：https://www.kaggle.com/code/jackiewu/qwen-1-8b-finetune ，我使用git clone 下来里面也是有这3个文件的，但是运行时候依然出现上面问题

**Comment by h66840** [comment]
您好，请问最后解决了吗
