### ISSUE TITLE
[BUG] 运行finetune_lora_ds.sh报错 SIGBUS

### ISSUE THREAD

**Issue by conkeur** [QwenLM/Qwen#683]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

sh finetune/finetune_lora_ds.sh后遇到报错
```
[2023-11-28 17:01:23,849] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-11-28 17:01:26,854] [INFO] [comm.py:637:init_distributed] cdb=None
[2023-11-28 17:01:26,854] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  4.01it/s]
trainable params: 1,387,790,336 || all params: 9,109,114,880 || trainable%: 15.235183157553942
Loading data...
Formatting inputs...Skip in lazy mode
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 68727) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=====================================================
finetune.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-28_17:02:54
  host      : d6c43f7437c9
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 68727)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 68727
=====================================================
```

### 期望行为 | Expected Behavior

正常使用多GPU微调

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 18.04
- Python:3.8.0
- Transformers:4.32.0
- PyTorch:2.0.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.7
四张 NVIDIA GeForce RTX 3090
运行free:
              total        used        free      shared  buff/cache   available
Mem:      263769132    27074940   120982232       72436   115711960   234787324
Swap:        999420       26112      973308
```

### 备注 | Anything else?

![image](https://github.com/QwenLM/Qwen/assets/88173440/fa1f64c9-2bc8-4a60-9456-5951dedd4e14)

**Comment by jklj077** [comment]
我们在多卡测试微调过程中没有遇到过该问题，也确实缺少18.04的环境来进行复现。

根据提供的日志，我们认为有以下可能的异常点：
- 如果是4卡进行分布式finetune，会开启4个进程，模型应会加载4次，日志中仅显示加载了一次，仅开启了一个进程。这可能跟环境变量的设置有关。
- `Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.` 内核版本不满足最低要求。
- SIGBUS错误，您是否在docker环境中运行？如果是，您可能需要增大共享内存大小(`--shm-size`)。其它可能原因还包括NCCL异常等，就不好排查了。

**Comment by PineappleWill** [comment]
> 我们在多卡测试微调过程中没有遇到过该问题，也确实缺少18.04的环境来进行复现。
> 
> 根据提供的日志，我们认为有以下可能的异常点：
> 
> * 如果是4卡进行分布式finetune，会开启4个进程，模型应会加载4次，日志中仅显示加载了一次，仅开启了一个进程。这可能跟环境变量的设置有关。
> * `Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.` 内核版本不满足最低要求。
> * SIGBUS错误，您是否在docker环境中运行？如果是，您可能需要增大共享内存大小(`--shm-size`)。其它可能原因还包括NCCL异常等，就不好排查了。

您好，内核版本这个问题我也遇到了，请问怎么解决呢

**Comment by Zerycii** [comment]
您好，内核版本这个问题我也遇到了，请问怎么解决呢
