### ISSUE TITLE
[BUG] <title>when I fine tune  qwen 7b int4 on the aliyun pai, the following error was encounters: OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by Miamas777** [QwenLM/Qwen#766]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior
```
/mnt/workspace> cd QwenCode
/mnt/workspace/QwenCode> bash finetune/finetune_qlora_single_gpu.sh
[2023-12-08 16:57:37,970] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/pai/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/pai/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/pai/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/pai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/pai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/pai/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/pai/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fce224c5eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pai/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/pai/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Qwen7BModel/Qwen-7B-Chat-Int4/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fce224c5eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 425, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/pai/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pai/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Qwen7BModel/Qwen-7B-Chat-Int4/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fce224c5eb0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 1bfaa56b-258a-4628-bb9d-80cad3218e74)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pai/lib/python3.9/site-packages/transformers/utils/hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/workspace/QwenCode/finetune.py", line 360, in <module>
    train()
  File "/mnt/workspace/QwenCode/finetune.py", line 286, in train
    config = transformers.AutoConfig.from_pretrained(
  File "/home/pai/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1007, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/pai/lib/python3.9/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/pai/lib/python3.9/site-packages/transformers/utils/hub.py", line 468, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Qwen7BModel/Qwen-7B-Chat-Int4 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```

### 复现方法 | Steps To Reproduce
```
 bash finetune/finetune_qlora_single_gpu.sh
.sh file is following:
#!/bin/bash
export CUDA_DEVICE_MAX_CONNECTIONS=1
DIR=`pwd`

MODEL="Qwen7BModel/Qwen-7B-Chat-Int4" # Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="finetune/data/train/SynData.json"

function usage() {
    echo '
Usage: bash finetune/finetune_qlora_single_gpu.sh [-m MODEL_PATH] [-d DATA_PATH]
'
}

while [[ "$1" != "" ]]; do
    case $1 in
        -m | --model )
            shift
            MODEL=$1
            ;;
        -d | --data )
            shift
            DATA=$1
            ;;
        -h | --help )
            usage
            exit 0
            ;;
        * )
            echo "Unknown argument ${1}"
            exit 1
            ;;
    esac
    shift
done

export CUDA_VISIBLE_DEVICES=0

# Remember to use --fp16 instead of --bf16 due to autogptq
python finetune.py \
  --model_name_or_path $MODEL \
  --data_path $DATA \
  --fp16 True \
  --output_dir output_qwen \
  --num_train_epochs 50 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 10 \
  --save_total_limit 10 \
  --learning_rate 3e-4 \
  --weight_decay 0.1 \
  --adam_beta2 0.95 \
  --warmup_ratio 0.01 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --report_to "none" \
  --model_max_length 512 \
  --lazy_preprocess True \
  --gradient_checkpointing \
  --use_lora \
  --q_lora \
  --deepspeed finetune/ds_config_zero2.json
```
### 运行环境 | Environment

```Markdown
Package                        Version
------------------------------ --------------------
absl-py                        1.4.0
accelerate                     0.25.0
addict                         2.4.0
aiofiles                       23.2.1
aiohttp                        3.8.4
aiosignal                      1.3.1
albumentations                 1.3.0
alibabacloud-credentials       0.3.2
alibabacloud-endpoint-util     0.0.3
alibabacloud-gateway-spi       0.0.1
alibabacloud-openapi-util      0.2.1
alibabacloud-pai-dlc20201203   1.0.0
alibabacloud-paistudio20220112 1.0.9
alibabacloud-tea               0.3.1
alibabacloud-tea-openapi       0.3.7
alibabacloud-tea-util          0.3.8
alibabacloud-tea-xml           0.0.2
alipai                         0.1.7
aliyun-log-python-sdk          0.8.5
aliyun-python-sdk-core         2.13.36
aliyun-python-sdk-kms          2.16.0
aliyun-python-sdk-sts          3.1.1
altair                         5.2.0
annotated-types                0.6.0
anyio                          3.7.1
argon2-cffi                    21.3.0
argon2-cffi-bindings           21.2.0
arrow                          1.2.3
astor                          0.8.1
astroid                        2.15.2
asttokens                      2.2.1
astunparse                     1.6.3
async-timeout                  4.0.2
attrs                          22.2.0
auto-gptq                      0.5.1
autopep8                       1.7.0
backcall                       0.2.0
beautifulsoup4                 4.12.2
bleach                         6.0.0
boltons                        23.0.0
brotlipy                       0.7.0
cachetools                     5.3.0
certifi                        2023.11.17
cffi                           1.15.1
charset-normalizer             2.0.4
click                          8.1.7
cloudpickle                    2.2.1
colorama                       0.4.6
coloredlogs                    15.0.1
comm                           0.1.3
common-io                      0.4.0+tunnel
conda                          23.7.4
conda-content-trust            0.1.3
conda-package-handling         1.9.0
configparser                   5.3.0
contextlib2                    21.6.0
contourpy                      1.0.7
crcmod                         1.7
cryptography                   37.0.4
cvxopt                         1.2.6
cycler                         0.11.0
Cython                         0.29.33
dataclasses                    0.6
datasets                       2.15.0
dateparser                     1.1.8
debugpy                        1.6.7
decorator                      5.1.1
decord                         0.6.0
deepspeed                      0.12.4
defusedxml                     0.7.1
descartes                      1.1.0
dill                           0.3.7
dnspython                      2.3.0
eas-prediction                 0.12
easy-rec                       0.1.6
einops                         0.6.0
elastic-transport              8.4.0
elasticsearch                  8.7.0
exceptiongroup                 1.2.0
executing                      1.2.0
fairscale                      0.4.13
fastapi                        0.104.1
fastjsonschema                 2.16.3
ffmpy                          0.3.1
filelock                       3.11.0
fire                           0.5.0
flake8                         6.0.0
fonttools                      4.39.3
fqdn                           1.5.1
frozenlist                     1.3.3
fsspec                         2023.10.0
future                         0.18.3
fvcore                         0.1.5.post20221221
gast                           0.4.0
gekko                          1.0.6
google-auth                    2.17.2
google-auth-oauthlib           1.0.0
googleapis-common-protos       1.59.0
gradio                         3.41.2
gradio_client                  0.5.0
graphviz                       0.20.1
grpcio                         1.53.0
h11                            0.14.0
h5py                           3.8.0
hjson                          3.1.0
httpcore                       1.0.2
httpx                          0.25.2
huggingface-hub                0.19.4
humanfriendly                  10.0
hyperopt                       0.1.2
idna                           3.4
imageio                        2.27.0
imgaug                         0.4.0
importlib-metadata             6.2.0
importlib-resources            5.12.0
iopath                         0.1.10
ipykernel                      6.22.0
ipython                        8.12.0
ipython-genutils               0.2.0
ipywidgets                     8.0.6
isoduration                    20.11.0
isort                          5.12.0
jedi                           0.18.2
Jinja2                         3.1.2
jmespath                       0.10.0
joblib                         1.2.0
json-tricks                    3.16.1
jsonpatch                      1.32
jsonpointer                    2.1
jsonschema                     4.17.3
jupyter                        1.0.0
jupyter_client                 8.1.0
jupyter-console                6.6.3
jupyter_core                   5.3.0
jupyter-events                 0.6.3
jupyter_server                 2.5.0
jupyter_server_terminals       0.4.4
jupyterlab-pygments            0.2.2
jupyterlab-widgets             3.0.7
kiwisolver                     1.4.4
latex2mathml                   3.77.0
lazy_loader                    0.2
lazy-object-proxy              1.6.0
llvmlite                       0.39.1
lmdb                           1.4.1
Markdown                       3.4.3
markdown-it-py                 3.0.0
MarkupSafe                     2.1.2
matplotlib                     3.5.2
matplotlib-inline              0.1.6
mccabe                         0.7.0
mdtex2html                     1.2.0
mdurl                          0.1.2
mistune                        2.0.5
mkl-fft                        1.3.8
mkl-random                     1.2.4
mkl-service                    2.4.0
mmcv-full                      1.7.0
mpmath                         1.3.0
multidict                      6.0.4
multiprocess                   0.70.15
mysql-connector-python         8.0.32
nbclassic                      0.5.5
nbclient                       0.7.3
nbconvert                      7.3.0
nbformat                       5.8.0
nest-asyncio                   1.5.6
networkx                       3.1
ninja                          1.11.1.1
notebook                       6.5.4
notebook_shim                  0.2.2
numba                          0.56.4
numpy                          1.23.0
nuscenes-devkit                1.1.10
nvidia-cublas-cu12             12.1.3.1
nvidia-cuda-cupti-cu12         12.1.105
nvidia-cuda-nvrtc-cu12         12.1.105
nvidia-cuda-runtime-cu12       12.1.105
nvidia-cudnn-cu12              8.9.2.26
nvidia-cufft-cu12              11.0.2.54
nvidia-curand-cu12             10.3.2.106
nvidia-cusolver-cu12           11.4.5.107
nvidia-cusparse-cu12           12.1.0.106
nvidia-dali-cuda110            1.24.0
nvidia-nccl-cu12               2.18.1
nvidia-nvjitlink-cu12          12.3.101
nvidia-nvtx-cu12               12.1.105
oauthlib                       3.2.2
opencv-contrib-python          4.6.0.66
opencv-python                  4.6.0.66
opencv-python-headless         4.6.0.66
opt-einsum                     3.3.0
optimum                        1.15.0
orjson                         3.9.10
oss2                           2.17.0
packaging                      23.0
pai-automl                     0.0.4
pai-easycv                     0.9.0
pai-nni                        2.6
pandas                         2.0.0
pandocfilters                  1.5.0
parso                          0.8.3
patsy                          0.5.3
peft                           0.7.0
pexpect                        4.8.0
pickleshare                    0.7.5
Pillow                         10.0.1
pip                            23.0.1
platformdirs                   3.2.0
plotly                         5.14.1
pluggy                         1.0.0
portalocker                    2.7.0
prettytable                    3.6.0
prometheus-client              0.16.0
prompt-toolkit                 3.0.38
protobuf                       3.20.3
psutil                         5.9.4
ptyprocess                     0.7.0
pure-eval                      0.2.2
py-cpuinfo                     9.0.0
pyaes                          1.6.1
pyarrow                        14.0.1
pyarrow-hotfix                 0.6
pyasn1                         0.4.8
pyasn1-modules                 0.2.8
pybind11                       2.10.1
pybind11-global                2.10.1
pyclipper                      1.3.0.post4
pycocotools                    2.0.6
pycodestyle                    2.10.0
pycosat                        0.6.4
pycparser                      2.21
pycryptodome                   3.17
pydantic                       1.9.0
pydantic_core                  2.14.5
pydub                          0.25.1
pyflakes                       3.0.1
Pygments                       2.14.0
pylint                         2.17.2
pymongo                        4.3.3
pynvml                         11.5.0
pyodps                         0.11.3.1
pyOpenSSL                      22.0.0
pyparsing                      3.0.9
pyquaternion                   0.9.9
pyrsistent                     0.19.3
PySocks                        1.7.1
python-dateutil                2.8.2
python-json-logger             2.0.7
python-multipart               0.0.6
PythonWebHDFS                  0.2.3
pytorch-metric-learning        2.1.0
pytorch-model-summary          0.1.2
pytz                           2023.3
pytz-deprecation-shim          0.1.0.post0
PyWavelets                     1.4.1
PyYAML                         6.0
pyzmq                          25.0.2
qtconsole                      5.4.2
QtPy                           2.3.1
qudida                         0.0.4
rapidfuzz                      2.15.0
regex                          2023.3.23
requests                       2.28.1
requests-oauthlib              1.3.1
responses                      0.23.1
rfc3339-validator              0.1.4
rfc3986-validator              0.1.1
rich                           13.7.0
rouge                          1.0.1
rsa                            4.9
ruamel.yaml                    0.17.21
ruamel.yaml.clib               0.2.6
safetensors                    0.4.1
sailfish                       1.0.1
schema                         0.7.5
scikit-image                   0.20.0
scikit-learn                   1.2.2
scipy                          1.9.1
seaborn                        0.12.2
semantic-version               2.10.0
Send2Trash                     1.8.0
sentencepiece                  0.1.99
setuptools                     65.6.3
Shapely                        1.8.5
shellingham                    1.5.4
simplejson                     3.19.1
six                            1.16.0
sklearn                        0.0.post1
sniffio                        1.3.0
soupsieve                      2.4
stack-data                     0.6.2
starlette                      0.27.0
statsmodels                    0.13.5
sympy                          1.12
tabulate                       0.9.0
tenacity                       8.2.2
tensorboard                    2.12.1
tensorboard-data-server        0.7.0
tensorboard-plugin-wit         1.8.1
termcolor                      2.2.0
terminado                      0.17.1
thop                           0.1.1.post2209072238
threadpoolctl                  3.1.0
tifffile                       2023.3.21
tiktoken                       0.5.2
timm                           0.5.4
tinycss2                       1.2.1
tokenizers                     0.13.3
toml                           0.10.2
tomli                          2.0.1
tomlkit                        0.12.0
toolz                          0.12.0
torch                          2.1.1+cu118
torchaudio                     2.1.1
torchinfo                      1.8.0
torchvision                    0.16.1
tornado                        6.2
tqdm                           4.65.0
training-utils                 1.0.6
traitlets                      5.9.0
transformers                   4.32.0
transformers-stream-generator  0.0.4
triton                         2.1.0
typer                          0.9.0
types-PyYAML                   6.0.12.9
typing_extensions              4.8.0
tzdata                         2023.3
tzlocal                        4.3
uri-template                   1.2.0
urllib3                        1.26.13
uvicorn                        0.24.0.post1
wcwidth                        0.2.6
webcolors                      1.13
webencodings                   0.5.1
websocket-client               1.5.1
websockets                     11.0.1
Werkzeug                       2.2.3
wget                           3.2
wheel                          0.38.4
widgetsnbextension             4.0.7
wrapt                          1.15.0
xgboost                        1.7.5
xlrd                           2.0.1
xtcocotools                    1.13
xxhash                         3.4.1
yacs                           0.1.8
yapf                           0.32.0
yarl                           1.8.2
zipp                           3.15.0
```

### 备注 | Anything else?

NVIDIA V100
memory 16G
Linux ubuntu 20.04
event: 2023-12-08 16:53:48: Readiness probe failed: Get "http://10.224.129.160:8888/dsw-290827/lab": dial tcp 10.224.129.160:8888: connect: connection refused

**Comment by jklj077** [comment]
Hi, it seemed to me that the script did not find the model checkpoint and files in `Qwen7BModel/Qwen-7B-Chat-Int4` as you specified. Please check if the files exist or download the model manually using the snapshot_download function provided by ModelScope as in README (in China mainland).
