### ISSUE TITLE
💡 [REQUEST] -<title>python  cli_demo.py --cpu-only

### ISSUE THREAD

**Issue by zengalanshuo** [QwenLM/Qwen#796]
### 实现PR | Implementation PR

Qwen-main>python  cli_demo.py --cpu-only
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "D:\Program Files\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "D:\Program Files\python\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\Program Files\python\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Program Files\python\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Program Files\python\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "D:\Program Files\python\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "D:\Program Files\python\lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001BA055F0610>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Program Files\python\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\Program Files\python\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Qwen/Qwen-7B-Chat/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001BA055F0610>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\file_download.py", line 425, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\Program Files\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "D:\Program Files\python\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Qwen/Qwen-7B-Chat/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001BA055F0610>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 9882be68-d30b-4b80-b9f1-6ab59e4eaebc)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\transformers\utils\hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Program Files\python\lib\site-packages\huggingface_hub\file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Qwen-main\cli_demo.py", line 210, in <module>
    main()
  File "Qwen-main\cli_demo.py", line 116, in main
    model, tokenizer, config = _load_model_tokenizer(args)
  File "Qwen-main\cli_demo.py", line 45, in _load_model_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "D:\Program Files\python\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 692, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "D:\Program Files\python\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1007, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Program Files\python\lib\site-packages\transformers\configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\Program Files\python\lib\site-packages\transformers\configuration_utils.py", line 675, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\Program Files\python\lib\site-packages\transformers\utils\hub.py", line 468, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Qwen/Qwen-7B-Chat is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

### 摘要 | Summary

china network 

### 基本示例 | Basic Example

cli-demo

### 缺陷 | Drawbacks

china network

**Comment by jklj077** [comment]
HuggingFace Hub访问失败了，建议手动下载模型相关文件，README中snapshot_download部分是国内下载的方式。

The scripts fails to connect to HuggingFace Hub. Please download the related files manually. If you encountered network issues from mainland China, you can try the snapshot_download provided by ModelScope as in the README.
