### ISSUE TITLE
[BUG] <title>按照官方提供的脚本运用推理后生成的tensor值出现异常

### ISSUE THREAD

**Issue by ruio248** [QwenLM/Qwen#815]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Traceback (most recent call last):
  File "/home/ruioliao/Qwen-72B-Chat/infer.py", line 33, in <module>
    response, history = model.chat(tokenizer, "你好", history=None,temperature =1)
  File "/home/ruioliao/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat/modeling_qwen.py", line 1137, in chat
    outputs = self.generate(
  File "/home/ruioliao/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat/modeling_qwen.py", line 1259, in generate
    return super().generate(
  File "/home/ruioliao/anaconda3/envs/llm/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ruioliao/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/home/ruioliao/anaconda3/envs/llm/lib/python3.9/site-packages/transformers/generation/utils.py", line 2760, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### 运行环境 | Environment

```Markdown
- OS:CentOS Linux release 7.9.2009 (Core)
- Python:3.9.0
- Transformers:4.32.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

### 备注 | Anything else?

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by xfcoms** [comment]
在windows10 环境下，qwen 72B，v100s*6， Transformers:4.36.1，PyTorch:2.1，cuda 12.1 python3.8.环境下，对每个模型文件进行hash比对过，同样存在RuntimeError: probability tensor contains either inf, nan or element < 0。

**Comment by jklj077** [comment]
@ruio248 @xfcoms 请问是否有调整过temperature、topp等参数？是使用的base模型还是chat模型？可否提供一些用于复现的数据样例？

**Comment by jklj077** [comment]
@ruio248 有装flash-attention吗？

**Comment by ruio248** [comment]
> @ruio248 有装flash-attention吗？
已经解决此问题，调整温度,top_p解决不了问题，我原来是在huggingface上下的模型，后来在魔塔上下就解决了这个问题，那个报错我觉得应该还是是我自己模型的权重出了问题
