### ISSUE TITLE
<help> ValueError: QWenLMHeadModel does not support Flash Attention 2.0 yet. 

### ISSUE THREAD

**Issue by txy6666yr** [QwenLM/Qwen#854]
使用框架微调qwen72B出现下面的问题：
```
12/23/2023 20:32:53 - WARNING - llmtuner.data.utils - Checksum failed: missing SHA-1 hash value in dataset_info.json.
12/23/2023 20:32:53 - INFO - llmtuner.data.loader - Loading dataset 1124_math.json...
12/23/2023 20:32:53 - WARNING - llmtuner.data.utils - Checksum failed: missing SHA-1 hash value in dataset_info.json.
Downloading data files: 100%|██████████| 1/1 [00:00<00:00, 14122.24it/s]
Extracting data files: 100%|██████████| 1/1 [00:00<00:00, 61.16it/s]
Generating train split: 273698 examples [00:08, 33933.76 examples/s]
12/23/2023 20:33:02 - INFO - llmtuner.model.patcher - Using FlashAttention-2 for faster training and inference.
The model was loaded with use_flash_attention_2=True, which is deprecated and may be removed in a future release. Please use `attn_implementation="flash_attention_2"` instead.
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/train_bash.py", line 15, in <module>
    main()
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/train_bash.py", line 5, in main
    run_exp()
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/llmtuner/train/tuner.py", line 26, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/llmtuner/train/sft/workflow.py", line 29, in run_sft
    model, tokenizer = load_model_and_tokenizer(model_args, finetuning_args, training_args.do_train)
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/llmtuner/model/loader.py", line 67, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3456, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1302, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1382, in _check_and_enable_flash_attn_2
    raise ValueError(
ValueError: QWenLMHeadModel does not support Flash Attention 2.0 yet. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new
```
参数:
```
--deepspeed scripts/configs/ds_config_zero2.json \
    --stage sft \
    --model_name_or_path $model \
    --do_train \
    --dataset ${dataset} \
    --cache_path $WORKDIR/data/cache_file/${dataset}_qwen \
    --template qwen \
    --finetuning_type full \
    --output_dir output/qwen72B_mn_${dataset} \
    --overwrite_output_dir True \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 1 \
    --save_steps 1000 \
    --learning_rate 1e-5 \
    --warmup_ratio 0.03\
    --num_train_epochs 3.0 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --cutoff_len 6144 \
    --plot_loss \
    --flash_attn \
    --bf16
```

**Comment by jklj077** [comment]
去掉--flash_attn， Qwen代码会识别自动开启。

**Comment by Andy1314Chen** [comment]
https://github.com/QwenLM/Qwen/blob/main/README_CN.md 文档中提到已经支持 flash-attention 2，但为什么我还是遇到这个 issue 相同的问题？

> 如果你的显卡支持fp16或bf16精度，我们还推荐安装[flash-attention](https://github.com/Dao-AILab/flash-attention)（当前已支持flash attention 2）来提高你的运行效率以及降低显存占用。(flash-attention只是可选项，不安装也可正常运行该项目)

**Comment by 6666ev** [comment]
> https://github.com/QwenLM/Qwen/blob/main/README_CN.md 文档中提到已经支持 flash-attention 2，但为什么我还是遇到这个 issue 相同的问题？
> 
> > 如果你的显卡支持fp16或bf16精度，我们还推荐安装[flash-attention](https://github.com/Dao-AILab/flash-attention)（当前已支持flash attention 2）来提高你的运行效率以及降低显存占用。(flash-attention只是可选项，不安装也可正常运行该项目)

同样的问题，没有加--flash_attn参数也报错
```
  WARNING: The script datasets-cli is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script trl is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script optimum-cli is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformer-engine 1.4.0+0fbc76a requires flash-attn!=2.0.9,!=2.1.0,<=2.4.2,>=2.0.6, but you have flash-attn 2.5.6 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2024-05-11 16:23:48,734  INFO /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/lake/__init__.py:23]  init AILake env...
INFO:lake:init AILake env...
2024-05-11 16:23:48,734  INFO /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/lake/__init__.py:35]  find libpangudfs_pangu_client.so.1 in the path /usr/local/lib64
INFO:lake:find libpangudfs_pangu_client.so.1 in the path /usr/local/lib64
2024-05-11 16:23:48,734  INFO /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/lake/__init__.py:35]  find libfslib_plugin_pangu.so in the path /usr/local/lib64
INFO:lake:find libfslib_plugin_pangu.so in the path /usr/local/lib64
2024-05-11 16:23:48,760  INFO /opt/conda/envs/python3.10.13/lib/python3.10/site-packages/lake/__init__.py:70]  init AILake env done.
INFO:lake:init AILake env done.
INFO:ai_scheduler_logger:/checkpoint/binary/train_package/../xdl_config_560536dc-6bd7-4ee4-b462-a5c0f641f8b3.json_b6d68a533442
INFO:ai_scheduler_logger:/checkpoint/binary/train_package/../xdl_config_560536dc-6bd7-4ee4-b462-a5c0f641f8b3.json_b6d68a533442
INFO:llmtuner.model.patcher:Using FlashAttention-2 for faster training and inference.
Traceback (most recent call last):
  File "/checkpoint/binary/train_package/src/generate.py", line 571, in <module>
    main()
  File "/checkpoint/binary/train_package/src/generate.py", line 562, in main
    model, tokenizer, processor = init_model(model_args, finetuning_args, infer_args)
  File "/checkpoint/binary/train_package/src/generate.py", line 133, in init_model
    model, tokenizer, processor = load_model_and_tokenizer(
  File "/checkpoint/binary/train_package/src/llmtuner/model/loader.py", line 177, in load_model_and_tokenizer
    model = load_model(tokenizer, model_args, finetuning_args, is_trainable, add_valuehead)
  File "/checkpoint/binary/train_package/src/llmtuner/model/loader.py", line 112, in load_model
    model = model_class.from_pretrained(model_args.model_name_or_path, config=config, **init_kwargs)
  File "/root/.local/lib/python3.10/site-packages/transformers/nebula_hub_utils.py", line 296, in _inner_fn
    return fn(args[0], pretrained_model_name_or_path, *args[2:], **kwargs)
  File "/root/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/.local/lib/python3.10/site-packages/transformers/nebula_hub_utils.py", line 296, in _inner_fn
    return fn(args[0], pretrained_model_name_or_path, *args[2:], **kwargs)
  File "/root/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3401, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/root/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1379, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/root/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1460, in _check_and_enable_flash_attn_2
    raise ValueError(
ValueError: QWenLMHeadModel does not support Flash Attention 2.0 yet. Please request to add support where the model is hosted, on its model hub page: https://huggingface.co/Qwen/Qwen-7B-Chat/discussions/new or in the Transformers GitHub repo: https://github.com/huggingface/transformers/issues/new
```

**Comment by jklj077** [comment]
Hi! 

Qwen1.0 uses custom modeling code and it will automatically use flash attention if it is available in the environment. You **shoud not** use it as you use other `transformers` models, as it is not compatible. Especially, you should not pass any arguments related to flash attention to the model constructor, including using the `transformers` tooling to control. If you are using third-party library, please double check that the library supports Qwen1.0 and related options are enabled.

We advise you to upgrade to Qwen1.5, which is integrated into `transformers` and fully compatible with the general practice in the community.
