### ISSUE TITLE
采用cpu方式推理Qwen-1_8B-Chat-Int4 报错

### ISSUE THREAD

**Issue by SiriusWy** [QwenLM/Qwen#884]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

模型可以正常加载：
> model = AutoModelForCausalLM.from_pretrained(model_path, device_map="cpu", trust_remote_code=True)

推理时报错：
> 请输入问题：hi
Traceback (most recent call last):
  File "/home/wy/qwen_lora/time_lora.py", line 25, in <module>
    response, history = model.chat(tokenizer, input_str, history=None)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat-Int4/modeling_qwen.py", line 1137, in chat
    outputs = self.generate(
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat-Int4/modeling_qwen.py", line 1259, in generate
    return super().generate(
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat-Int4/modeling_qwen.py", line 1043, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat-Int4/modeling_qwen.py", line 891, in forward
    outputs = block(
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat-Int4/modeling_qwen.py", line 610, in forward
    attn_outputs = self.attn(
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Qwen-1_8B-Chat-Int4/modeling_qwen.py", line 416, in forward
    mixed_x_layer = self.c_attn(hidden_states)
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/qwen3/lib/python3.10/site-packages/auto_gptq/nn_modules/qlinear/qlinear_cuda_old.py", line 273, in forward
    out = torch.matmul(x, weight)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### 运行环境 | Environment

```Markdown
- OS:
- Python: 3.10
- Transformers: 4.36.2
- PyTorch: 2.0.1
- auto-gptq: 0.6.0+cu118
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): cu118
```

**Comment by jklj077** [comment]
autogptq的CPU推理是实验性功能，现在transformers也不支持autogptq进行CPU推理，从我们的角度就是目前**不受支持**。

如果一定要用，可以尝试用autogptq自己的from_quantized然后设置use_qigen为True，但from_quantized还需要个quantize_config.json，这个你可以自己从config.json里拼出来。实验性功能不一定哪有问题，建议寻求autogptq维护人员的帮助。
