### ISSUE TITLE
TypeError: QWenLMHeadModel.forward() got an unexpected keyword argument 'decoder_input_ids'[BUG] <title>

### ISSUE THREAD

**Issue by AlexJJJChen** [QwenLM/Qwen#901]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Traceback (most recent call last):
  File "/home/jianc/benchmark/finetune_s2s_model.py", line 249, in <module>
    training_output = trainer.train()
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/transformers/trainer.py", line 1854, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/transformers/trainer.py", line 2735, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/transformers/trainer.py", line 2758, in compute_loss
    outputs = model(**inputs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/peft/peft_model.py", line 1249, in forward
    return self.base_model(
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 103, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/benchmark-llm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
TypeError: QWenLMHeadModel.forward() got an unexpected keyword argument 'decoder_input_ids'

### 运行环境 | Environment

```Markdown
- OS:22.04.3
- Python:3.10.0
- Transformers:4.36.2
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.2
```

**Comment by jklj077** [comment]
请使用示例微调代码。Qwen是decoder-only模型，不是sequence-to-sequence模型，不能传decoder_input_ids。
