### ISSUE TITLE
[BUG] <单卡lora微调>

### ISSUE THREAD

**Issue by yoohhwz** [QwenLM/Qwen#946]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

执行 bash finetune/finetune_lora_single_gpu.sh 后报错如下：
[2024-01-11 18:31:56,087] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The model is automatically converting to fp16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 8/8 [00:08<00:00,  1.02s/it]
trainable params: 143,130,624 || all params: 7,864,455,168 || trainable%: 1.8199687192876373
Loading data...
Formatting inputs...Skip in lazy mode
No protocol specified
Using /home/ubuntu/.cache/torch_extensions/py310_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/.cache/torch_extensions/py310_cu117/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /data/anaconda3/envs/qwen-lora/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/TH -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/THC -isystem /data/anaconda3/envs/qwen-lora/include -isystem /data/anaconda3/envs/qwen-lora/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -std=c++17 -c /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/data/anaconda3/envs/qwen-lora/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/TH -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/THC -isystem /data/anaconda3/envs/qwen-lora/include -isystem /data/anaconda3/envs/qwen-lora/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -std=c++17 -c /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
cc1plus: fatal error: cuda_runtime.h: No such file or directory
compilation terminated.
[2/3] c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/TH -isystem /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/include/THC -isystem /data/anaconda3/envs/qwen-lora/include -isystem /data/anaconda3/envs/qwen-lora/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/app/Qwen-main/finetune.py", line 374, in <module>
    train()
  File "/data/app/Qwen-main/finetune.py", line 367, in train
    trainer.train()
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/transformers/trainer.py", line 1687, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 1219, in prepare
    result = self._prepare_deepspeed(*args)
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 1604, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 304, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1208, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1285, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 458, in load
    return self.jit_load(verbose)
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 502, in jit_load
    op_module = load(name=self.name,
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data/anaconda3/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'

### 复现方法 | Steps To Reproduce

安装环境：
conda install pytorch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 pytorch-cuda=11.8 cudatoolkit==11.8 -c pytorch -c nvidia
conda install nvidia/label/cuda-11.8.0::cuda-nvcc

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.1.2
>>> 
>>> print(torch.cuda.is_available())
True
>>> 
>>> print(torch.version.cuda)
11.8
>>> print(torch.backends.cudnn.version())
8700

执行bash finetune/finetune_lora_single_gpu.sh 微调脚本后报错

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.10
- Transformers:4.32.0
- PyTorch:2.1.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):11.8
```

**Comment by jklj077** [comment]
您好，我们不建议现在使用conda中这样安装的cuda套件，目前conda的环境变量管理存在一些问题，会导致torch extension编译时，无法正确识别cuda library path，导致一系列怪异的问题。

- 简单直接的解决办法是在系统中安装cuda 11.8套件（可以与现有的cuda 11.7并存，对于ubuntu系统，需要时通过update-alternatives切换）
- 备选的解决办法是，通过`conda env config vars`功能手动配置PATH、LD_LIBRARY_PATH等环境变量，建议查阅有关文档说明。

**Comment by LIXUEGUANG002** [comment]
我也报错 但是我报错的是 bash finetune/finetune_lora_single_gpu.sh
[2024-01-13 17:55:37,244] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
**finetune/finetune_lora_single_gpu.sh: 第 62 行： 1491143 已杀死**               python finetune.py --model_name_or_path $MODEL --data_path $DATA --bf16 True --output_dir output_qwen --num_train_epochs 5 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 1000 --save_total_limit 10 --learning_rate 3e-4 --weight_decay 0.1 --adam_beta2 0.95 --warmup_ratio 0.01 --lr_scheduler_type "cosine" --logging_steps 1 --report_to "none" --model_max_length 512 --lazy_preprocess True --gradient_checkpointing --use_lora

**Comment by yoohhwz** [comment]
> 我也报错 但是我报错的是 bash finetune/finetune_lora_single_gpu.sh [2024-01-13 17:55:37,244] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect) The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained". Try importing flash-attention for faster inference... Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm **finetune/finetune_lora_single_gpu.sh: 第 62 行： 1491143 已杀死** python finetune.py --model_name_or_path $MODEL --data_path $DATA --bf16 True --output_dir output_qwen --num_train_epochs 5 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 1000 --save_total_limit 10 --learning_rate 3e-4 --weight_decay 0.1 --adam_beta2 0.95 --warmup_ratio 0.01 --lr_scheduler_type "cosine" --logging_steps 1 --report_to "none" --model_max_length 512 --lazy_preprocess True --gradient_checkpointing --use_lora

我也遇到了  好像是修改 finetune.py中 的 device_map = None 改为 device_map  = 'auto'

**Comment by LIXUEGUANG002** [comment]
> > 我也报错 但是我报错的是 bash finetune/finetune_lora_single_gpu.sh [2024-01-13 17:55:37,244] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect) The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained". Try importing flash-attention for faster inference... Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm **finetune/finetune_lora_single_gpu.sh: 第 62 行： 1491143 已杀死** python finetune.py --model_name_or_path $MODEL --data_path $DATA --bf16 True --output_dir output_qwen --num_train_epochs 5 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --gradient_accumulation_steps 8 --evaluation_strategy "no" --save_strategy "steps" --save_steps 1000 --save_total_limit 10 --learning_rate 3e-4 --weight_decay 0.1 --adam_beta2 0.95 --warmup_ratio 0.01 --lr_scheduler_type "cosine" --logging_steps 1 --report_to "none" --model_max_length 512 --lazy_preprocess True --gradient_checkpointing --use_lora
> 
> 我也遇到了 好像是修改 finetune.py中 的 device_map = None 改为 device_map = 'auto'

就是您的说这种，我按照您说的修改了一下，结果跑通啦 太谢谢啦！！！

**Comment by ZHANGJINKUI** [comment]
> 您好，我们不建议现在使用conda中这样安装的cuda套件，目前conda的环境变量管理存在一些问题，会导致torch extension编译时，无法正确识别cuda library path，导致一系列怪异的问题。
> 
> * 简单直接的解决办法是在系统中安装cuda 11.8套件（可以与现有的cuda 11.7并存，对于ubuntu系统，需要时通过update-alternatives切换）
> * 备选的解决办法是，通过`conda env config vars`功能手动配置PATH、LD_LIBRARY_PATH等环境变量，建议查阅有关文档说明。

您好，具体应该怎么解决呀，我也遇到这个一模一样的问题了

**Comment by yoohhwz** [comment]
> > 您好，我们不建议现在使用conda中这样安装的cuda套件，目前conda的环境变量管理存在一些问题，会导致torch extension编译时，无法正确识别cuda library path，导致一系列怪异的问题。
> > 
> > * 简单直接的解决办法是在系统中安装cuda 11.8套件（可以与现有的cuda 11.7并存，对于ubuntu系统，需要时通过update-alternatives切换）
> > * 备选的解决办法是，通过`conda env config vars`功能手动配置PATH、LD_LIBRARY_PATH等环境变量，建议查阅有关文档说明。
> 
> 您好，具体应该怎么解决呀，我也遇到这个一模一样的问题了

你可以单独在本机上安装cuda就能解决，注意好对应的cuda版本问题
