### ISSUE TITLE
[BUG] qwen1.8b微调后 调用模型tokenizer报错ModuleNotFoundError: No module named 'transformers_modules.qwen_1'

### ISSUE THREAD

**Issue by tungsten106** [QwenLM/Qwen#966]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Traceback (most recent call last):
  File "/data/yxl/Qwen-1.8B/qwen_1_8b_service_adgen.py", line 42, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
  File "/data/yxl/miniconda3/envs/LLM-qwen18b/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 710, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/data/yxl/miniconda3/envs/LLM-qwen18b/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 497, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/data/yxl/miniconda3/envs/LLM-qwen18b/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 199, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/data/yxl/miniconda3/envs/LLM-qwen18b/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.qwen_1'

### 期望行为 | Expected Behavior

之前也试过微调qwen7b，微调后的模型可以正常调用tokenizer，目前只有qwen1.8b的模型微调后出现这个问题

### 运行环境 | Environment

```Markdown
- OS: Rocky Linux release 8.8 (Green Obsidian)
- Python: 3.8.18
- Transformers: 4.32.0 / 4.33.2
- PyTorch: 2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`): 12.1
```

**Comment by jklj077** [comment]
checkpoint文件夹里不要有点号，比如"Qwen-1.8B" -> "Qwen-1_8B"

**Comment by tungsten106** [comment]
> checkpoint文件夹里不要有点号，比如"Qwen-1.8B" -> "Qwen-1_8B"

确实是这个问题，感谢！

**Comment by Hfriendship** [comment]
这也太坑爹了，打了点号
