### ISSUE TITLE
[BUG] libcudart.so.12: cannot open shared object file: No such file or directory ​

### ISSUE THREAD

**Issue by ArlanCooper** [QwenLM/Qwen#978]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我这边执行命令:
```
from modelscope import AutoTokenizer, AutoModelForCausalLM

# Note: The default behavior now has injection attack prevention off.
tokenizer = AutoTokenizer.from_pretrained("/data/share/rwq/Qwen-72B-Chat-Int4", revision='master', trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    "/data/share/rwq/Qwen-72B-Chat-Int4", revision='master',
    device_map="auto",
    trust_remote_code=True
).eval()
response, history = model.chat(tokenizer, "你好", history=None)
print(response)

```

报错：
```
ImportError                               Traceback (most recent call last)
Cell In[3], line 4
      1 # Note: The default behavior now has injection attack prevention off.
      2 tokenizer = AutoTokenizer.from_pretrained("/data/share/rwq/Qwen-72B-Chat-Int4", revision='master', trust_remote_code=True)
----> 4 model = AutoModelForCausalLM.from_pretrained(
      5     "/data/share/rwq/Qwen-72B-Chat-Int4", revision='master',
      6     device_map="auto",
      7     trust_remote_code=True
      8 ).eval()
      9 response, history = model.chat(tokenizer, "你好", history=None)
     10 print(response)

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/modelscope/utils/hf_util.py:111, in get_wrapped_class.<locals>.ClassWrapper.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    108 else:
    109     model_dir = pretrained_model_name_or_path
--> 111 module_obj = module_class.from_pretrained(model_dir, *model_args,
    112                                           **kwargs)
    114 if module_class.__name__.startswith('AutoModel'):
    115     module_obj.model_dir = model_dir

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:561, in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    559     else:
    560         cls.register(config.__class__, model_class, exist_ok=True)
--> 561     return model_class.from_pretrained(
    562         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    563     )
    564 elif type(config) in cls._model_mapping.keys():
    565     model_class = _get_model_class(config, cls._model_mapping)

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/modelscope/utils/hf_util.py:74, in patch_model_base.<locals>.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
     72 else:
     73     model_dir = pretrained_model_name_or_path
---> 74 return ori_from_pretrained(cls, model_dir, *model_args, **kwargs)

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/transformers/modeling_utils.py:3545, in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   3542 if quantization_config is None:
   3543     quantization_config = AwqConfig.from_dict(config.quantization_config)
-> 3545 model, has_been_replaced = replace_with_awq_linear(
   3546     model, quantization_config=quantization_config, modules_to_not_convert=modules_to_not_convert
   3547 )
   3548 model._is_quantized_training_enabled = False
   3550 if not has_been_replaced:

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/transformers/integrations/awq.py:81, in replace_with_awq_linear(model, modules_to_not_convert, quantization_config, current_key_name, has_been_replaced)
     76     raise ValueError(
     77         "AWQ (either `autoawq` or `llmawq`) is not available. Please install it with `pip install autoawq` or check out the installation guide in https://github.com/mit-han-lab/llm-awq"
     78     )
     80 if backend == AwqBackendPackingMethod.AUTOAWQ:
---> 81     from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
     82 elif backend == AwqBackendPackingMethod.LLMAWQ:
     83     from awq.quantize.qmodule import WQLinear

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/awq/__init__.py:2
      1 __version__ = "0.1.8"
----> 2 from awq.models.auto import AutoAWQForCausalLM

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/awq/models/__init__.py:1
----> 1 from .mpt import MptAWQForCausalLM
      2 from .llama import LlamaAWQForCausalLM
      3 from .opt import OptAWQForCausalLM

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/awq/models/mpt.py:1
----> 1 from .base import BaseAWQForCausalLM
      2 from transformers.models.mpt.modeling_mpt import MptBlock as OldMptBlock, MptForCausalLM
      4 class MptAWQForCausalLM(BaseAWQForCausalLM):

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/awq/models/base.py:16
     13 import transformers
     14 from transformers.modeling_utils import shard_checkpoint
---> 16 from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
     17 from awq.utils.module import (
     18     get_named_linears,
     19     set_op_by_name,
     20     exclude_layers_to_not_quantize,
     21 )
     22 from transformers import (
     23     AutoConfig,
     24     PreTrainedModel,
   (...)
     27     CLIPImageProcessor,
     28 )

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/awq/modules/linear.py:4
      2 import torch
      3 import torch.nn as nn
----> 4 import awq_inference_engine  # with CUDA kernels
      7 def make_divisible(c, divisor):
      8     return (c + divisor - 1) // divisor

ImportError: libcudart.so.12: cannot open shared object file: No such file or directory



```

### 期望行为 | Expected Behavior

不报错

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 20.04
- Python: 3.10.12
- Transformers:4.36.2
- PyTorch:2.1.0
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):118
```

**Comment by jklj077** [comment]
modelscope的请去modelscope repo哈

**Comment by ArlanCooper** [comment]
> modelscope的请去modelscope repo哈

一样的，我使用transformer，报同样的错误:
```

from transformers import AutoTokenizer, AutoModelForCausalLM

# Note: The default behavior now has injection attack prevention off.
tokenizer = AutoTokenizer.from_pretrained("/data/share/rwq/Qwen-72B-Chat-Int4", trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    "/data/share/rwq/Qwen-72B-Chat-Int4",
    device_map="auto",
    trust_remote_code=True
).eval()

```

报错信息:


```
ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 model = AutoModelForCausalLM.from_pretrained(
      2     "/data/share/rwq/Qwen-72B-Chat-Int4",
      3     device_map="auto",
      4     trust_remote_code=True
      5 ).eval()

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:561, in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    559     else:
    560         cls.register(config.__class__, model_class, exist_ok=True)
--> 561     return model_class.from_pretrained(
    562         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    563     )
    564 elif type(config) in cls._model_mapping.keys():
    565     model_class = _get_model_class(config, cls._model_mapping)

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/transformers/modeling_utils.py:3545, in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   3542 if quantization_config is None:
   3543     quantization_config = AwqConfig.from_dict(config.quantization_config)
-> 3545 model, has_been_replaced = replace_with_awq_linear(
   3546     model, quantization_config=quantization_config, modules_to_not_convert=modules_to_not_convert
   3547 )
   3548 model._is_quantized_training_enabled = False
   3550 if not has_been_replaced:

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/transformers/integrations/awq.py:81, in replace_with_awq_linear(model, modules_to_not_convert, quantization_config, current_key_name, has_been_replaced)
     76     raise ValueError(
     77         "AWQ (either `autoawq` or `llmawq`) is not available. Please install it with `pip install autoawq` or check out the installation guide in https://github.com/mit-han-lab/llm-awq"
     78     )
     80 if backend == AwqBackendPackingMethod.AUTOAWQ:
---> 81     from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
     82 elif backend == AwqBackendPackingMethod.LLMAWQ:
     83     from awq.quantize.qmodule import WQLinear

File ~/work/conda/envs/qwen/lib/python3.10/site-packages/awq/modules/linear.py:4
      2 import torch
      3 import torch.nn as nn
----> 4 import awq_inference_engine  # with CUDA kernels
      7 def make_divisible(c, divisor):
      8     return (c + divisor - 1) // divisor

ImportError: libcudart.so.12: cannot open shared object file: No such file or directory


```

**Comment by jklj077** [comment]
Qwen-72B-Chat-Int4是gptq哈。如果使用非官方模型，特别是我们未说明支持的方法或模型，建议您找相应来源解答您的问题。
根据日志，该错误是从awq中抛出来的，建议找awq。

**Comment by weiwei0519** [comment]
用gptq也是报同样的错误：

File "/home/python/AI_project/gpt-doc-qa-uat/qa_manager/doc_manager.py", line 93, in init_model
    local_doc_qa.init_cfg()
  File "/home/python/AI_project/gpt-doc-qa-uat/chains/local_doc_qa.py", line 668, in init_cfg
    self.llm_qwen.load_model(model_name_or_path=llm_model_dict["Qwen1.5-72B-Chat-GPTQ-Int4"],
  File "/home/python/AI_project/gpt-doc-qa-uat/models/Qwen_llm.py", line 123, in load_model
    self.model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3159, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/optimum/gptq/quantizer.py", line 43, in <module>
    from auto_gptq import exllama_set_max_input_length
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/auto_gptq/__init__.py", line 4, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/auto_gptq/utils/peft_utils.py", line 20, in <module>
    from ..nn_modules.qlinear.qlinear_exllama import QuantLinear as QuantLinearExllama
  File "/usr/local/python/anaconda3/envs/chatglm_langchain/lib/python3.9/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllama.py", line 14, in <module>
    from exllama_kernels import make_q4, q4_matmul
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
