### ISSUE TITLE
您好，请问可以对Q-Lora微调过的模型再次进行微调吗？

### ISSUE THREAD

**Issue by zhengzehao123** [QwenLM/Qwen#986]
请问可以对Q-Lora微调过的模型再次进行微调吗
我在再次微调时出现了错误：
Traceback (most recent call last):
  File "/root/zhengzh/Bert-TextClassification/Qwen/finetune.py", line 382, in <module>
    LLM_train(args,[1,1,1,1,1],2)
  File "/root/zhengzh/Bert-TextClassification/Qwen/finetune.py", line 318, in LLM_train
    model = AutoPeftModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/auto.py", line 103, in from_pretrained
    return cls._target_peft_class.from_pretrained(
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/peft_model.py", line 351, in from_pretrained
    model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/peft_model.py", line 1043, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/peft_model.py", line 125, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 90, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 247, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, **optional_kwargs)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 202, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
  File "/root/miniconda3/envs/berttc/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 355, in _create_new_module
    raise ValueError(
ValueError: Target module QuantLinear() is not supported. Currently, only the following modules are supported: `torch.nn.Linear`, `torch.nn.Embedding`, `torch.nn.Conv2d`, `transformers.pytorch_utils.Conv1D`.

如果不支持对Q-Lora微调过的模型再次微调，Lora微调后将微调参数与原模型参数合并，对新的模型进行微调是否可行？您有没有其他方法或建议？

**Comment by jklj077** [comment]
finetune.py不支持(Q-)LoRA on (Q-)LoRA这种配置。

> LoRA微调后将微调参数与原模型参数合并，对新的模型进行微调是否可行

这个流程一般是okay的。

LoRA还有一种工作流是对**base模型**进行多次微调，得到多个adapter，推理时通过[add_weighted_adapter](https://huggingface.co/docs/peft/v0.7.1/en/package_reference/lora#peft.LoraModel.add_weighted_adapter)组合多个adapter，但目前本repo未有示例，这种建议也调研看看。
