### ISSUE TITLE
[BUG] <关于使用finetune_lora_ds.sh显存爆炸的问题>

### ISSUE THREAD

**Issue by yoohhwz** [QwenLM/Qwen#995]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

在使用lora对微调后并合并的模型文件进行二次微调的时候遇到显存爆炸的情况，我是一机多卡，两张32G的V100，训练阶段显存爆炸后遇到如下错误：
bash finetune/finetune_lora_ds.sh 
[2024-01-23 11:24:19,300] torch.distributed.run: [WARNING] 
[2024-01-23 11:24:19,300] torch.distributed.run: [WARNING] *****************************************
[2024-01-23 11:24:19,300] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-01-23 11:24:19,300] torch.distributed.run: [WARNING] *****************************************
[2024-01-23 11:24:21,344] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-23 11:24:21,523] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-01-23 11:24:22,466] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-01-23 11:24:22,466] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
[2024-01-23 11:24:22,697] [INFO] [comm.py:637:init_distributed] cdb=None
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00,  8.63it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00,  8.26it/s]
trainable params: 1,387,790,336 || all params: 9,109,114,880 || trainable%: 15.235183157553942
Loading data...
Formatting inputs...Skip in lazy mode
trainable params: 1,387,790,336 || all params: 9,109,114,880 || trainable%: 15.235183157553942
Using /home/ubuntu/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/.cache/torch_extensions/py310_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.0702824592590332 seconds
Using /home/ubuntu/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ubuntu/.cache/torch_extensions/py310_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.06588077545166016 seconds
/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py:96: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = get_accelerator().IntTensor([0])
/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py:96: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  self._dummy_overflow_buf = get_accelerator().IntTensor([0])
  0%|                                                                                                                                                                | 0/100 [00:00<?, ?it/s]/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
  1%|█▌                                                                                                                                                      | 1/100 [00:01<02:54,  1.76s/it]tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 0.4191, 'learning_rate': 0, 'epoch': 1.0}                                                                                                                                           
  1%|█▌                                                                                                                                                      | 1/100 [00:01<02:54,  1.76s/it]Traceback (most recent call last):
  File "/data/app/Qwen-main/finetune.py", line 374, in <module>
    train()
  File "/data/app/Qwen-main/finetune.py", line 367, in train
    trainer.train()
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/transformers/trainer.py", line 1837, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/transformers/trainer.py", line 2693, in training_step
    self.accelerator.backward(loss)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/accelerate/accelerator.py", line 1958, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1964, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 2040, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 886, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1399, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 915, in reduce_independent_p_g_buckets_and_remove_grads
    self.reduce_ipg_grads()
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1350, in reduce_ipg_grads
    self.average_tensor(self.ipg_buffer[self.ipg_index])
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1110, in average_tensor
    self.allreduce_and_scatter(buckets[bucket_key],
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1014, in allreduce_and_scatter
    self.allreduce_and_copy_with_multiple_ranks(small_bucket,
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 987, in allreduce_and_copy_with_multiple_ranks
    allreduced = self.allreduce_bucket(small_bucket, log=log, divide=divide, process_group=process_group)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1464, in allreduce_bucket
    tensor = self.flatten(bucket)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/_utils.py", line 498, in _flatten_dense_tensors
    return torch._C._nn.flatten_dense_tensors(tensors)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 274.00 MiB. GPU 1 has a total capacty of 31.74 GiB of which 60.38 MiB is free. Including non-PyTorch memory, this process has 31.67 GiB memory in use. Of the allocated memory 29.24 GiB is allocated by PyTorch, and 1.97 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-01-23 11:24:49,334] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 523571 closing signal SIGTERM
[2024-01-23 11:24:49,548] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 523572) of binary: /data/anaconda/envs/qwen-lora/bin/python3.10
Traceback (most recent call last):
  File "/data/anaconda/envs/qwen-lora/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/anaconda/envs/qwen-lora/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-23_11:24:49
  host      : 10-60-69-204
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 523572)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### 复现方法 | Steps To Reproduce

首先针对原Qwen-7B模型进行lora微调，微调后的文件使用lora合并，合并之后运行微调的模型没有问题
然后针对微调并合并后的这个模型文件进行二次微调的时候出现了显存爆炸问题，问题log如上。

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04
- Python:3.10.13
- Transformers:4.32.0
- PyTorch:2.1.2+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
- nvcc -V  
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
- nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100S-PCIE-32GB          Off | 00000000:00:03.0 Off |                  Off |
| N/A   30C    P0              25W / 250W |      5MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100S-PCIE-32GB          Off | 00000000:00:08.0 Off |                    0 |
| N/A   29C    P0              23W / 250W |      5MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1441      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A      1441      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by zhengzehao123** [comment]
我也有这个问题

**Comment by yoohhwz** [comment]
> 我也有这个问题

解决了吗

**Comment by zhengzehao123** [comment]
> > 我也有这个问题
> 
> 解决了吗

还没有，我觉得 #619 应该也是同样的问题，不过没有给出答案。如果有解决方案了能麻烦分享一下吗，我如果找到原因了也会在这发一下
